auto-sync-files:
  - suite/auto-sync/*

LLVM-core-files:
  - MC*.[ch]

LLVM-generated-files:
  - arch/*/*.inc

Documentation:
  - '**/*.md'

CS-core-files:
  - cs*.[ch]
  - SStream.[ch]
  - utis.[ch]
  - MathExtras.h
  - Mapping.[ch]
  - LEB128.h
  - cstool/cstool.[ch]
  - cstool/getopt.[ch]
  - include/capstone/capstone.h
  - include/capstone/cs_operand.h
  - include/capstone/platform.h

ARM:
  - arch/ARM/*
  - cstool/cstool_arm.c
  - include/capstone/arm.h
  - suite/MC/ARM/*
  - tests/test_arm.c

AArch64:
  - arch/AArch64/*
  - cstool/cstool_aarch64.c
  - include/capstone/aarch64.h
  - suite/MC/AArch64/*
  - tests/test_aarch64.c

Alpha:
  - arch/Alpha/*
  - cstool/cstool_alpha.c
  - include/capstone/alpha.h
  - suite/MC/Alpha/*
  - tests/test_alpha.c

BPF:
  - arch/BPF/*
  - cstool/cstool_bpf.c
  - include/capstone/bpf.h
  - suite/MC/BPF/*
  - tests/test_bpf.c

EVM:
  - arch/EVM/*
  - cstool/cstool_evm.c
  - include/capstone/evm.h
  - tests/test_evm.c

HPPA:
  - arch/HPPA/*
  - cstool/cstool_hppa.c
  - include/capstone/hppa.h
  - suite/MC/HPPA/*
  - tests/test_hppa.c

M680X:
  - arch/M680X/*
  - cstool/cstool_m680x.c
  - include/capstone/m680x.h
  - tests/test_m680x.c

M68K:
  - arch/M68K/*
  - cstool/cstool_m68k.c
  - include/capstone/m68k.h
  - tests/test_m68k.c

MOS65XX:
  - arch/MOS65XX/*
  - cstool/cstool_mos65xx.c
  - include/capstone/mos65xx.h
  - tests/test_mos65xx.c

Mips:
  - arch/Mips/*
  - cstool/cstool_mips.c
  - include/capstone/mips.h
  - suite/MC/Mips/*
  - tests/test_mips.c

PowerPC:
  - arch/PowerPC/*
  - cstool/cstool_powerpc.c
  - include/capstone/ppc.h
  - suite/MC/PowerPC/*
  - tests/test_powerpc.c

RISCV:
  - arch/RISCV/*
  - cstool/cstool_riscv.c
  - include/capstone/riscv.h
  - suite/MC/RISCV/*
  - tests/test_riscv.c

SH:
  - arch/SH/*
  - cstool/cstool_sh.c
  - include/capstone/sh.h
  - tests/test_sh.c

Sparc:
  - arch/Sparc/*
  - cstool/cstool_sparc.c
  - include/capstone/sparc.h
  - suite/MC/Sparc/*
  - tests/test_sparc.c

SystemZ:
  - arch/SystemZ/*
  - cstool/cstool_systemz.c
  - include/capstone/systemz.h
  - suite/MC/SystemZ/*
  - tests/test_systemz.c

TMS320C64x:
  - arch/TMS320C6x/*
  - cstool/cstool_tms320c64x.c
  - include/capstone/tms320x64x.h
  - tests/test_tms320c64x.c

TriCore:
  - arch/TriCore/*
  - cstool/cstool_tricore.c
  - include/capstone/tricore.h
  - suite/MC/Tricore/*
  - tests/test_tricore.c

WASM:
  - arch/WASM/*
  - cstool/cstool_wasm.c
  - include/capstone/wasm.h
  - tests/test_wasm.c

X86:
  - arch/X86/*
  - cstool/cstool_x86.c
  - include/capstone/x86.h
  - suite/MC/X86/*
  - tests/test_x86.c

XCore:
  - arch/XCore/*
  - cstool/cstool_xcore.c
  - include/capstone/xcore.h
  - tests/test_xcore.c
