/* Capstone Disassembly Engine, https://www.capstone-engine.org */
/* By Nguyen Anh Quynh <aquynh@gmail.com>, 2013-2022, */
/*    Rot127 <unisono@quyllur.org> 2022-2023 */

{{{ /* RISCV_PHI (0) */
 0
}}},
{{{ /* RISCV_INLINEASM (1) */
 0
}}},
{{{ /* RISCV_INLINEASM_BR (2) */
 0
}}},
{{{ /* RISCV_CFI_INSTRUCTION (3) */
 0
}}},
{{{ /* RISCV_EH_LABEL (4) */
 0
}}},
{{{ /* RISCV_GC_LABEL (5) */
 0
}}},
{{{ /* RISCV_ANNOTATION_LABEL (6) */
 0
}}},
{{{ /* RISCV_KILL (7) */
 0
}}},
{{{ /* RISCV_EXTRACT_SUBREG (8) */
 0
}}},
{{{ /* RISCV_INSERT_SUBREG (9) */
 0
}}},
{{{ /* RISCV_IMPLICIT_DEF (10) */
 0
}}},
{{{ /* RISCV_SUBREG_TO_REG (11) */
 0
}}},
{{{ /* RISCV_COPY_TO_REGCLASS (12) */
 0
}}},
{{{ /* RISCV_DBG_VALUE (13) */
 0
}}},
{{{ /* RISCV_DBG_LABEL (14) */
 0
}}},
{{{ /* RISCV_REG_SEQUENCE (15) */
 0
}}},
{{{ /* RISCV_COPY (16) */
 0
}}},
{{{ /* RISCV_BUNDLE (17) */
 0
}}},
{{{ /* RISCV_LIFETIME_START (18) */
 0
}}},
{{{ /* RISCV_LIFETIME_END (19) */
 0
}}},
{{{ /* RISCV_STACKMAP (20) */
 0
}}},
{{{ /* RISCV_FENTRY_CALL (21) */
 0
}}},
{{{ /* RISCV_PATCHPOINT (22) */
 0
}}},
{{{ /* RISCV_LOAD_STACK_GUARD (23) */
 0
}}},
{{{ /* RISCV_STATEPOINT (24) */
 0
}}},
{{{ /* RISCV_LOCAL_ESCAPE (25) */
 0
}}},
{{{ /* RISCV_FAULTING_OP (26) */
 0
}}},
{{{ /* RISCV_PATCHABLE_OP (27) */
 0
}}},
{{{ /* RISCV_PATCHABLE_FUNCTION_ENTER (28) */
 0
}}},
{{{ /* RISCV_PATCHABLE_RET (29) */
 0
}}},
{{{ /* RISCV_PATCHABLE_FUNCTION_EXIT (30) */
 0
}}},
{{{ /* RISCV_PATCHABLE_TAIL_CALL (31) */
 0
}}},
{{{ /* RISCV_PATCHABLE_EVENT_CALL (32) */
 0
}}},
{{{ /* RISCV_PATCHABLE_TYPED_EVENT_CALL (33) */
 0
}}},
{{{ /* RISCV_ICALL_BRANCH_FUNNEL (34) */
 0
}}},
{{{ /* RISCV_G_ADD (35) */
 0
}}},
{{{ /* RISCV_G_SUB (36) */
 0
}}},
{{{ /* RISCV_G_MUL (37) */
 0
}}},
{{{ /* RISCV_G_SDIV (38) */
 0
}}},
{{{ /* RISCV_G_UDIV (39) */
 0
}}},
{{{ /* RISCV_G_SREM (40) */
 0
}}},
{{{ /* RISCV_G_UREM (41) */
 0
}}},
{{{ /* RISCV_G_AND (42) */
 0
}}},
{{{ /* RISCV_G_OR (43) */
 0
}}},
{{{ /* RISCV_G_XOR (44) */
 0
}}},
{{{ /* RISCV_G_IMPLICIT_DEF (45) */
 0
}}},
{{{ /* RISCV_G_PHI (46) */
 0
}}},
{{{ /* RISCV_G_FRAME_INDEX (47) */
 0
}}},
{{{ /* RISCV_G_GLOBAL_VALUE (48) */
 0
}}},
{{{ /* RISCV_G_EXTRACT (49) */
 0
}}},
{{{ /* RISCV_G_UNMERGE_VALUES (50) */
 0
}}},
{{{ /* RISCV_G_INSERT (51) */
 0
}}},
{{{ /* RISCV_G_MERGE_VALUES (52) */
 0
}}},
{{{ /* RISCV_G_BUILD_VECTOR (53) */
 0
}}},
{{{ /* RISCV_G_BUILD_VECTOR_TRUNC (54) */
 0
}}},
{{{ /* RISCV_G_CONCAT_VECTORS (55) */
 0
}}},
{{{ /* RISCV_G_PTRTOINT (56) */
 0
}}},
{{{ /* RISCV_G_INTTOPTR (57) */
 0
}}},
{{{ /* RISCV_G_BITCAST (58) */
 0
}}},
{{{ /* RISCV_G_INTRINSIC_TRUNC (59) */
 0
}}},
{{{ /* RISCV_G_INTRINSIC_ROUND (60) */
 0
}}},
{{{ /* RISCV_G_LOAD (61) */
 0
}}},
{{{ /* RISCV_G_SEXTLOAD (62) */
 0
}}},
{{{ /* RISCV_G_ZEXTLOAD (63) */
 0
}}},
{{{ /* RISCV_G_STORE (64) */
 0
}}},
{{{ /* RISCV_G_ATOMIC_CMPXCHG_WITH_SUCCESS (65) */
 0
}}},
{{{ /* RISCV_G_ATOMIC_CMPXCHG (66) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_XCHG (67) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_ADD (68) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_SUB (69) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_AND (70) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_NAND (71) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_OR (72) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_XOR (73) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_MAX (74) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_MIN (75) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_UMAX (76) */
 0
}}},
{{{ /* RISCV_G_ATOMICRMW_UMIN (77) */
 0
}}},
{{{ /* RISCV_G_BRCOND (78) */
 0
}}},
{{{ /* RISCV_G_BRINDIRECT (79) */
 0
}}},
{{{ /* RISCV_G_INTRINSIC (80) */
 0
}}},
{{{ /* RISCV_G_INTRINSIC_W_SIDE_EFFECTS (81) */
 0
}}},
{{{ /* RISCV_G_ANYEXT (82) */
 0
}}},
{{{ /* RISCV_G_TRUNC (83) */
 0
}}},
{{{ /* RISCV_G_CONSTANT (84) */
 0
}}},
{{{ /* RISCV_G_FCONSTANT (85) */
 0
}}},
{{{ /* RISCV_G_VASTART (86) */
 0
}}},
{{{ /* RISCV_G_VAARG (87) */
 0
}}},
{{{ /* RISCV_G_SEXT (88) */
 0
}}},
{{{ /* RISCV_G_ZEXT (89) */
 0
}}},
{{{ /* RISCV_G_SHL (90) */
 0
}}},
{{{ /* RISCV_G_LSHR (91) */
 0
}}},
{{{ /* RISCV_G_ASHR (92) */
 0
}}},
{{{ /* RISCV_G_ICMP (93) */
 0
}}},
{{{ /* RISCV_G_FCMP (94) */
 0
}}},
{{{ /* RISCV_G_SELECT (95) */
 0
}}},
{{{ /* RISCV_G_UADDO (96) */
 0
}}},
{{{ /* RISCV_G_UADDE (97) */
 0
}}},
{{{ /* RISCV_G_USUBO (98) */
 0
}}},
{{{ /* RISCV_G_USUBE (99) */
 0
}}},
{{{ /* RISCV_G_SADDO (100) */
 0
}}},
{{{ /* RISCV_G_SADDE (101) */
 0
}}},
{{{ /* RISCV_G_SSUBO (102) */
 0
}}},
{{{ /* RISCV_G_SSUBE (103) */
 0
}}},
{{{ /* RISCV_G_UMULO (104) */
 0
}}},
{{{ /* RISCV_G_SMULO (105) */
 0
}}},
{{{ /* RISCV_G_UMULH (106) */
 0
}}},
{{{ /* RISCV_G_SMULH (107) */
 0
}}},
{{{ /* RISCV_G_FADD (108) */
 0
}}},
{{{ /* RISCV_G_FSUB (109) */
 0
}}},
{{{ /* RISCV_G_FMUL (110) */
 0
}}},
{{{ /* RISCV_G_FMA (111) */
 0
}}},
{{{ /* RISCV_G_FDIV (112) */
 0
}}},
{{{ /* RISCV_G_FREM (113) */
 0
}}},
{{{ /* RISCV_G_FPOW (114) */
 0
}}},
{{{ /* RISCV_G_FEXP (115) */
 0
}}},
{{{ /* RISCV_G_FEXP2 (116) */
 0
}}},
{{{ /* RISCV_G_FLOG (117) */
 0
}}},
{{{ /* RISCV_G_FLOG2 (118) */
 0
}}},
{{{ /* RISCV_G_FLOG10 (119) */
 0
}}},
{{{ /* RISCV_G_FNEG (120) */
 0
}}},
{{{ /* RISCV_G_FPEXT (121) */
 0
}}},
{{{ /* RISCV_G_FPTRUNC (122) */
 0
}}},
{{{ /* RISCV_G_FPTOSI (123) */
 0
}}},
{{{ /* RISCV_G_FPTOUI (124) */
 0
}}},
{{{ /* RISCV_G_SITOFP (125) */
 0
}}},
{{{ /* RISCV_G_UITOFP (126) */
 0
}}},
{{{ /* RISCV_G_FABS (127) */
 0
}}},
{{{ /* RISCV_G_FCANONICALIZE (128) */
 0
}}},
{{{ /* RISCV_G_GEP (129) */
 0
}}},
{{{ /* RISCV_G_PTR_MASK (130) */
 0
}}},
{{{ /* RISCV_G_BR (131) */
 0
}}},
{{{ /* RISCV_G_INSERT_VECTOR_ELT (132) */
 0
}}},
{{{ /* RISCV_G_EXTRACT_VECTOR_ELT (133) */
 0
}}},
{{{ /* RISCV_G_SHUFFLE_VECTOR (134) */
 0
}}},
{{{ /* RISCV_G_CTTZ (135) */
 0
}}},
{{{ /* RISCV_G_CTTZ_ZERO_UNDEF (136) */
 0
}}},
{{{ /* RISCV_G_CTLZ (137) */
 0
}}},
{{{ /* RISCV_G_CTLZ_ZERO_UNDEF (138) */
 0
}}},
{{{ /* RISCV_G_CTPOP (139) */
 0
}}},
{{{ /* RISCV_G_BSWAP (140) */
 0
}}},
{{{ /* RISCV_G_FCEIL (141) */
 0
}}},
{{{ /* RISCV_G_FCOS (142) */
 0
}}},
{{{ /* RISCV_G_FSIN (143) */
 0
}}},
{{{ /* RISCV_G_FSQRT (144) */
 0
}}},
{{{ /* RISCV_G_FFLOOR (145) */
 0
}}},
{{{ /* RISCV_G_ADDRSPACE_CAST (146) */
 0
}}},
{{{ /* RISCV_G_BLOCK_ADDR (147) */
 0
}}},
{{{ /* RISCV_ADJCALLSTACKDOWN (148) */
 0
}}},
{{{ /* RISCV_ADJCALLSTACKUP (149) */
 0
}}},
{{{ /* RISCV_BuildPairF64Pseudo (150) */
 0
}}},
{{{ /* RISCV_PseudoAtomicLoadNand32 (151) */
 0
}}},
{{{ /* RISCV_PseudoAtomicLoadNand64 (152) */
 0
}}},
{{{ /* RISCV_PseudoBR (153) */
 0
}}},
{{{ /* RISCV_PseudoBRIND (154) */
 0
}}},
{{{ /* RISCV_PseudoCALL (155) */
 0
}}},
{{{ /* RISCV_PseudoCALLIndirect (156) */
 0
}}},
{{{ /* RISCV_PseudoCmpXchg32 (157) */
 0
}}},
{{{ /* RISCV_PseudoCmpXchg64 (158) */
 0
}}},
{{{ /* RISCV_PseudoLA (159) */
 0
}}},
{{{ /* RISCV_PseudoLI (160) */
 0
}}},
{{{ /* RISCV_PseudoLLA (161) */
 0
}}},
{{{ /* RISCV_PseudoMaskedAtomicLoadAdd32 (162) */
 0
}}},
{{{ /* RISCV_PseudoMaskedAtomicLoadMax32 (163) */
 0
}}},
{{{ /* RISCV_PseudoMaskedAtomicLoadMin32 (164) */
 0
}}},
{{{ /* RISCV_PseudoMaskedAtomicLoadNand32 (165) */
 0
}}},
{{{ /* RISCV_PseudoMaskedAtomicLoadSub32 (166) */
 0
}}},
{{{ /* RISCV_PseudoMaskedAtomicLoadUMax32 (167) */
 0
}}},
{{{ /* RISCV_PseudoMaskedAtomicLoadUMin32 (168) */
 0
}}},
{{{ /* RISCV_PseudoMaskedAtomicSwap32 (169) */
 0
}}},
{{{ /* RISCV_PseudoMaskedCmpXchg32 (170) */
 0
}}},
{{{ /* RISCV_PseudoRET (171) */
 0
}}},
{{{ /* RISCV_PseudoTAIL (172) */
 0
}}},
{{{ /* RISCV_PseudoTAILIndirect (173) */
 0
}}},
{{{ /* RISCV_Select_FPR32_Using_CC_GPR (174) */
 0
}}},
{{{ /* RISCV_Select_FPR64_Using_CC_GPR (175) */
 0
}}},
{{{ /* RISCV_Select_GPR_Using_CC_GPR (176) */
 0
}}},
{{{ /* RISCV_SplitF64Pseudo (177) */
 0
}}},
{ /* RISCV_ADD (178) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_ADDI (179) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_ADDIW (180) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_ADDW (181) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOADD_D (182) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOADD_D_AQ (183) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOADD_D_AQ_RL (184) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOADD_D_RL (185) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOADD_W (186) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOADD_W_AQ (187) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOADD_W_AQ_RL (188) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOADD_W_RL (189) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOAND_D (190) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOAND_D_AQ (191) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOAND_D_AQ_RL (192) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOAND_D_RL (193) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOAND_W (194) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOAND_W_AQ (195) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOAND_W_AQ_RL (196) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOAND_W_RL (197) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAXU_D (198) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAXU_D_AQ (199) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAXU_D_AQ_RL (200) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAXU_D_RL (201) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAXU_W (202) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAXU_W_AQ (203) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAXU_W_AQ_RL (204) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAXU_W_RL (205) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAX_D (206) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAX_D_AQ (207) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAX_D_AQ_RL (208) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAX_D_RL (209) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAX_W (210) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAX_W_AQ (211) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAX_W_AQ_RL (212) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMAX_W_RL (213) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMINU_D (214) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMINU_D_AQ (215) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMINU_D_AQ_RL (216) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMINU_D_RL (217) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMINU_W (218) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMINU_W_AQ (219) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMINU_W_AQ_RL (220) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMINU_W_RL (221) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMIN_D (222) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMIN_D_AQ (223) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMIN_D_AQ_RL (224) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMIN_D_RL (225) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMIN_W (226) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMIN_W_AQ (227) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMIN_W_AQ_RL (228) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOMIN_W_RL (229) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOOR_D (230) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOOR_D_AQ (231) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOOR_D_AQ_RL (232) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOOR_D_RL (233) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOOR_W (234) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOOR_W_AQ (235) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOOR_W_AQ_RL (236) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOOR_W_RL (237) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOSWAP_D (238) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOSWAP_D_AQ (239) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOSWAP_D_AQ_RL (240) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOSWAP_D_RL (241) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOSWAP_W (242) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOSWAP_W_AQ (243) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOSWAP_W_AQ_RL (244) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOSWAP_W_RL (245) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOXOR_D (246) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOXOR_D_AQ (247) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOXOR_D_AQ_RL (248) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOXOR_D_RL (249) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOXOR_W (250) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOXOR_W_AQ (251) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOXOR_W_AQ_RL (252) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AMOXOR_W_RL (253) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AND (254) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_ANDI (255) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_AUIPC (256) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_BEQ (257) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_BGE (258) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_BGEU (259) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_BLT (260) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_BLTU (261) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_BNE (262) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_CSRRC (263) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_CSRRCI (264) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_CSRRS (265) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_CSRRSI (266) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_CSRRW (267) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_CSRRWI (268) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_ADD (269) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_ADDI (270) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_ADDI16SP (271) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_ADDI4SPN (272) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_ADDIW (273) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_ADDW (274) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_AND (275) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_ANDI (276) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_BEQZ (277) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_BNEZ (278) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_EBREAK (279) */
{
  { 0 }
}},
{ /* RISCV_C_FLD (280) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_FLDSP (281) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_FLW (282) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_FLWSP (283) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_FSD (284) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_FSDSP (285) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_FSW (286) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_FSWSP (287) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_J (288) */
{
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_JAL (289) */
{
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_JALR (290) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_JR (291) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_LD (292) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_LDSP (293) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_LI (294) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_LUI (295) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_LW (296) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_LWSP (297) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_MV (298) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_NOP (299) */
{
  { 0 }
}},
{ /* RISCV_C_OR (300) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_SD (301) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_SDSP (302) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_SLLI (303) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_SRAI (304) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_SRLI (305) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_SUB (306) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_SUBW (307) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_SW (308) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_SWSP (309) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_C_UNIMP (310) */
{
  { 0 }
}},
{ /* RISCV_C_XOR (311) */
{
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ | CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_DIV (312) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_DIVU (313) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_DIVUW (314) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_DIVW (315) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_EBREAK (316) */
{
  { 0 }
}},
{ /* RISCV_ECALL (317) */
{
  { 0 }
}},
{ /* RISCV_FADD_D (318) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FADD_S (319) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCLASS_D (320) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCLASS_S (321) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_D_L (322) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_D_LU (323) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_D_S (324) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_D_W (325) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_D_WU (326) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_LU_D (327) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_LU_S (328) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_L_D (329) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_L_S (330) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_S_D (331) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_S_L (332) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_S_LU (333) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_S_W (334) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_S_WU (335) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_WU_D (336) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_WU_S (337) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_W_D (338) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FCVT_W_S (339) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FDIV_D (340) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FDIV_S (341) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FENCE (342) */
{
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FENCE_I (343) */
{
  { 0 }
}},
{ /* RISCV_FENCE_TSO (344) */
{
  { 0 }
}},
{ /* RISCV_FEQ_D (345) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FEQ_S (346) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FLD (347) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FLE_D (348) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FLE_S (349) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FLT_D (350) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FLT_S (351) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FLW (352) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMADD_D (353) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMADD_S (354) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMAX_D (355) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMAX_S (356) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMIN_D (357) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMIN_S (358) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMSUB_D (359) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMSUB_S (360) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMUL_D (361) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMUL_S (362) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMV_D_X (363) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMV_W_X (364) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMV_X_D (365) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FMV_X_W (366) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FNMADD_D (367) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FNMADD_S (368) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FNMSUB_D (369) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FNMSUB_S (370) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSD (371) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSGNJN_D (372) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSGNJN_S (373) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSGNJX_D (374) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSGNJX_S (375) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSGNJ_D (376) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSGNJ_S (377) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSQRT_D (378) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSQRT_S (379) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSUB_D (380) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSUB_S (381) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_FSW (382) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_f32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_JAL (383) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_JALR (384) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LB (385) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i8, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LBU (386) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i8, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LD (387) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LH (388) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i16, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LHU (389) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i16, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LR_D (390) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LR_D_AQ (391) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LR_D_AQ_RL (392) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LR_D_RL (393) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LR_W (394) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LR_W_AQ (395) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LR_W_AQ_RL (396) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LR_W_RL (397) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LUI (398) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LW (399) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_LWU (400) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_MRET (401) */
{
  { 0 }
}},
{ /* RISCV_MUL (402) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_MULH (403) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_MULHSU (404) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_MULHU (405) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_MULW (406) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_OR (407) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_ORI (408) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_REM (409) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_REMU (410) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_REMUW (411) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_REMW (412) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SB (413) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i8, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SC_D (414) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SC_D_AQ (415) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SC_D_AQ_RL (416) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SC_D_RL (417) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SC_W (418) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SC_W_AQ (419) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SC_W_AQ_RL (420) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SC_W_RL (421) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SD (422) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SFENCE_VMA (423) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SH (424) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i16, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SLL (425) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SLLI (426) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SLLIW (427) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SLLW (428) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SLT (429) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SLTI (430) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SLTIU (431) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SLTU (432) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SRA (433) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SRAI (434) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SRAIW (435) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SRAW (436) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SRET (437) */
{
  { 0 }
}},
{ /* RISCV_SRL (438) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SRLI (439) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SRLIW (440) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SRLW (441) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SUB (442) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SUBW (443) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_i64, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_SW (444) */
{
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_i32, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_UNIMP (445) */
{
  { 0 }
}},
{ /* RISCV_URET (446) */
{
  { 0 }
}},
{ /* RISCV_WFI (447) */
{
  { 0 }
}},
{ /* RISCV_XOR (448) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_XORI (449) */
{
  { CS_OP_REG, CS_AC_WRITE, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_REG, CS_AC_READ, { CS_DATA_TYPE_Untyped, CS_DATA_TYPE_LAST },  }, /*  */
  { CS_OP_IMM, CS_AC_READ, { CS_DATA_TYPE_Other, CS_DATA_TYPE_LAST },  }, /*  */
  { 0 }
}},
{ /* RISCV_INSTRUCTION_LIST_END (450) */
{
  { 0 }
}},
