#ifndef CAPSTONE_LOONGARCH_H
#define CAPSTONE_LOONGARCH_H

/* Capstone Disassembly Engine */
/* By Jiajie Chen <c@jia.je> 2024 */
/*    Yanglin Xun <1109673069@qq.com>, 2024 */

#ifdef __cplusplus
extern "C" {
#endif

#if !defined(_MSC_VER) || !defined(_KERNEL_MODE)
#include <stdint.h>
#endif

#include "platform.h"
#include "cs_operand.h"

/// Operand type for instruction's operands
typedef enum loongarch_op_type {
	LoongArch_OP_INVALID = CS_OP_INVALID, ///< Invalid
	LoongArch_OP_REG = CS_OP_REG,	      ///< Register operand
	LoongArch_OP_IMM = CS_OP_IMM,	      ///< Immediate operand
	LoongArch_OP_MEM = CS_OP_MEM,	      ///< Memory operand
} loongarch_op_type;

/// Instruction's operand referring to memory
/// This is associated with LOONGARCH_OP_MEM operand type above
typedef struct loongarch_op_mem {
	unsigned int base;  ///< base register
	unsigned int index; ///< index register
	int64_t disp;	    ///< displacement/offset value
} loongarch_op_mem;

/// Instruction operand
typedef struct cs_loongarch_op {
	loongarch_op_type type;	      //< operand type
	union {
		unsigned int reg;     /// register value for REG operand
		int64_t imm;	      /// immediate value for IMM operand
		loongarch_op_mem mem; /// base/disp value for MEM operand
	};

	/// How is this operand accessed? (READ, WRITE or READ|WRITE)
	/// NOTE: this field is irrelevant if engine is compiled in DIET mode.
	uint8_t access;
} cs_loongarch_op;

/// LoongArch instruction formats. To get details about them please
/// refer to `LoongArchInstrFormats.td` in LLVM.
typedef enum {
	// generated content <LoongArchGenCSInsnFormatsEnum.inc> begin
	// clang-format off

LoongArch_INSN_FORM_PSEUDO,
	LoongArch_INSN_FORM_FMT3R,
	LoongArch_INSN_FORM_FMT2RI12,
	LoongArch_INSN_FORM_FMT2RI5,
	LoongArch_INSN_FORM_FMT2RI16,
	LoongArch_INSN_FORM_FMT3RI2,
	LoongArch_INSN_FORM_NODSTFMT2RI4,
	LoongArch_INSN_FORM_FMT1RI8,
	LoongArch_INSN_FORM_FMT2RI4,
	LoongArch_INSN_FORM_NODSTFMT1RI4,
	LoongArch_INSN_FORM_NODSTFMT1RI5I4,
	LoongArch_INSN_FORM_FMTASRT,
	LoongArch_INSN_FORM_FMTI26,
	LoongArch_INSN_FORM_FPFMTBR,
	LoongArch_INSN_FORM_FMT1RI21,
	LoongArch_INSN_FORM_FMT2R,
	LoongArch_INSN_FORM_FMTI15,
	LoongArch_INSN_FORM_FMTBSTR_D,
	LoongArch_INSN_FORM_FMTBSTR_W,
	LoongArch_INSN_FORM_FMT3RI3,
	LoongArch_INSN_FORM_FMTCACOP,
	LoongArch_INSN_FORM_FMTCSR,
	LoongArch_INSN_FORM_FMTCSRXCHG,
	LoongArch_INSN_FORM_FMTI32,
	LoongArch_INSN_FORM_FPFMT2R,
	LoongArch_INSN_FORM_FPFMT3R,
	LoongArch_INSN_FORM_FPFMTFCMP,
	LoongArch_INSN_FORM_FPFMTMEM,
	LoongArch_INSN_FORM_FPFMT2RI12,
	LoongArch_INSN_FORM_FPFMT4R,
	LoongArch_INSN_FORM_FPFMTMOV,
	LoongArch_INSN_FORM_FPFMTFSEL,
	LoongArch_INSN_FORM_FMTINVTLB,
	LoongArch_INSN_FORM_FMTJISCR,
	LoongArch_INSN_FORM_FMT2RI8,
	LoongArch_INSN_FORM_FMTLDPTE,
	LoongArch_INSN_FORM_FMT2RI14,
	LoongArch_INSN_FORM_FMT1RI20,
	LoongArch_INSN_FORM_FMTGR2SCR,
	LoongArch_INSN_FORM_FMTSCR2GR,
	LoongArch_INSN_FORM_FMTPRELD,
	LoongArch_INSN_FORM_FMTPRELDX,
	LoongArch_INSN_FORM_FMT2RI3,
	LoongArch_INSN_FORM_FMT2RI6,
	LoongArch_INSN_FORM_FMT1RI4,
	LoongArch_INSN_FORM_FMT3R_VVV,
	LoongArch_INSN_FORM_FMT2RI5_VVI,
	LoongArch_INSN_FORM_FMT2RI8_VVI,
	LoongArch_INSN_FORM_FMT2RI3_VVI,
	LoongArch_INSN_FORM_FMT2RI6_VVI,
	LoongArch_INSN_FORM_FMT2RI4_VVI,
	LoongArch_INSN_FORM_FMT4R_VVVV,
	LoongArch_INSN_FORM_FMT2R_VV,
	LoongArch_INSN_FORM_FMT2R_XX,
	LoongArch_INSN_FORM_FMT2RI4_VRI,
	LoongArch_INSN_FORM_FMT2RI1_VRI,
	LoongArch_INSN_FORM_FMT2RI3_VRI,
	LoongArch_INSN_FORM_FMT2RI2_VRI,
	LoongArch_INSN_FORM_FMT2RI12_VRI,
	LoongArch_INSN_FORM_FMT1RI13_VI,
	LoongArch_INSN_FORM_FMT2RI9_VRI,
	LoongArch_INSN_FORM_FMT2RI11_VRI,
	LoongArch_INSN_FORM_FMT2RI10_VRI,
	LoongArch_INSN_FORM_FMT3R_VRR,
	LoongArch_INSN_FORM_FMT2RI4_RVI,
	LoongArch_INSN_FORM_FMT2RI1_RVI,
	LoongArch_INSN_FORM_FMT2RI3_RVI,
	LoongArch_INSN_FORM_FMT2RI2_RVI,
	LoongArch_INSN_FORM_FMT2R_VR,
	LoongArch_INSN_FORM_FMT2RI1_VVI,
	LoongArch_INSN_FORM_FMT2RI2_VVI,
	LoongArch_INSN_FORM_FMT3R_VVR,
	LoongArch_INSN_FORM_FMT2R_CV,
	LoongArch_INSN_FORM_FMT2RI7_VVI,
	LoongArch_INSN_FORM_FMT2RI8I4_VRII,
	LoongArch_INSN_FORM_FMT2RI8I1_VRII,
	LoongArch_INSN_FORM_FMT2RI8I3_VRII,
	LoongArch_INSN_FORM_FMT2RI8I2_VRII,
	LoongArch_INSN_FORM_NODSTFMT2R,
	LoongArch_INSN_FORM_NODSTFMT1R,
	LoongArch_INSN_FORM_FMTMFTOP,
	LoongArch_INSN_FORM_FMTMTTOP,
	LoongArch_INSN_FORM_NODSTFMT1RI3,
	LoongArch_INSN_FORM_NODSTFMT1RI6,
	LoongArch_INSN_FORM_NODSTFMT1RI5,
	LoongArch_INSN_FORM_FMT1RI5I8,
	LoongArch_INSN_FORM_FMT3R_XXX,
	LoongArch_INSN_FORM_FMT2RI5_XXI,
	LoongArch_INSN_FORM_FMT2RI8_XXI,
	LoongArch_INSN_FORM_FMT2RI3_XXI,
	LoongArch_INSN_FORM_FMT2RI6_XXI,
	LoongArch_INSN_FORM_FMT2RI4_XXI,
	LoongArch_INSN_FORM_FMT4R_XXXX,
	LoongArch_INSN_FORM_FMT2RI2_XRI,
	LoongArch_INSN_FORM_FMT2RI3_XRI,
	LoongArch_INSN_FORM_FMT2RI2_XXI,
	LoongArch_INSN_FORM_FMT2RI12_XRI,
	LoongArch_INSN_FORM_FMT1RI13_XI,
	LoongArch_INSN_FORM_FMT2RI9_XRI,
	LoongArch_INSN_FORM_FMT2RI11_XRI,
	LoongArch_INSN_FORM_FMT2RI10_XRI,
	LoongArch_INSN_FORM_FMT3R_XRR,
	LoongArch_INSN_FORM_FMT2RI2_RXI,
	LoongArch_INSN_FORM_FMT2RI3_RXI,
	LoongArch_INSN_FORM_FMT2RI1_XXI,
	LoongArch_INSN_FORM_FMT2R_XR,
	LoongArch_INSN_FORM_FMT3R_XXR,
	LoongArch_INSN_FORM_FMT2R_CX,
	LoongArch_INSN_FORM_FMT2RI7_XXI,
	LoongArch_INSN_FORM_FMT2RI8I5_XRII,
	LoongArch_INSN_FORM_FMT2RI8I2_XRII,
	LoongArch_INSN_FORM_FMT2RI8I4_XRII,
	LoongArch_INSN_FORM_FMT2RI8I3_XRII,

	// clang-format on
	// generated content <LoongArchGenCSInsnFormatsEnum.inc> end
} loongarch_insn_form;

/// Supplemental info for LoongArch instructions
typedef struct {
	loongarch_insn_form form; ///< Instruction form
	enum cs_ac_type
		memory_access; ///< Memory access (none/read/write/read+write)
} loongarch_suppl_info;

/// Instruction structure
typedef struct cs_loongarch {
	/// The instruction format. Can be use to determine the bit encoding of the instruction.
	loongarch_insn_form format;

	/// Number of operands of this instruction,
	/// or 0 when instruction has no operand.
	uint8_t op_count;
	cs_loongarch_op operands[8]; ///< operands for this instruction.
} cs_loongarch;

/// LoongArch registers
typedef enum loongarch_reg {
	// generated content <LoongArchGenCSRegEnum.inc> begin
	// clang-format off

	LoongArch_REG_INVALID = 0,
	LoongArch_REG_F0 = 1,
	LoongArch_REG_F1 = 2,
	LoongArch_REG_F2 = 3,
	LoongArch_REG_F3 = 4,
	LoongArch_REG_F4 = 5,
	LoongArch_REG_F5 = 6,
	LoongArch_REG_F6 = 7,
	LoongArch_REG_F7 = 8,
	LoongArch_REG_F8 = 9,
	LoongArch_REG_F9 = 10,
	LoongArch_REG_F10 = 11,
	LoongArch_REG_F11 = 12,
	LoongArch_REG_F12 = 13,
	LoongArch_REG_F13 = 14,
	LoongArch_REG_F14 = 15,
	LoongArch_REG_F15 = 16,
	LoongArch_REG_F16 = 17,
	LoongArch_REG_F17 = 18,
	LoongArch_REG_F18 = 19,
	LoongArch_REG_F19 = 20,
	LoongArch_REG_F20 = 21,
	LoongArch_REG_F21 = 22,
	LoongArch_REG_F22 = 23,
	LoongArch_REG_F23 = 24,
	LoongArch_REG_F24 = 25,
	LoongArch_REG_F25 = 26,
	LoongArch_REG_F26 = 27,
	LoongArch_REG_F27 = 28,
	LoongArch_REG_F28 = 29,
	LoongArch_REG_F29 = 30,
	LoongArch_REG_F30 = 31,
	LoongArch_REG_F31 = 32,
	LoongArch_REG_FCC0 = 33,
	LoongArch_REG_FCC1 = 34,
	LoongArch_REG_FCC2 = 35,
	LoongArch_REG_FCC3 = 36,
	LoongArch_REG_FCC4 = 37,
	LoongArch_REG_FCC5 = 38,
	LoongArch_REG_FCC6 = 39,
	LoongArch_REG_FCC7 = 40,
	LoongArch_REG_FCSR0 = 41,
	LoongArch_REG_FCSR1 = 42,
	LoongArch_REG_FCSR2 = 43,
	LoongArch_REG_FCSR3 = 44,
	LoongArch_REG_R0 = 45,
	LoongArch_REG_R1 = 46,
	LoongArch_REG_R2 = 47,
	LoongArch_REG_R3 = 48,
	LoongArch_REG_R4 = 49,
	LoongArch_REG_R5 = 50,
	LoongArch_REG_R6 = 51,
	LoongArch_REG_R7 = 52,
	LoongArch_REG_R8 = 53,
	LoongArch_REG_R9 = 54,
	LoongArch_REG_R10 = 55,
	LoongArch_REG_R11 = 56,
	LoongArch_REG_R12 = 57,
	LoongArch_REG_R13 = 58,
	LoongArch_REG_R14 = 59,
	LoongArch_REG_R15 = 60,
	LoongArch_REG_R16 = 61,
	LoongArch_REG_R17 = 62,
	LoongArch_REG_R18 = 63,
	LoongArch_REG_R19 = 64,
	LoongArch_REG_R20 = 65,
	LoongArch_REG_R21 = 66,
	LoongArch_REG_R22 = 67,
	LoongArch_REG_R23 = 68,
	LoongArch_REG_R24 = 69,
	LoongArch_REG_R25 = 70,
	LoongArch_REG_R26 = 71,
	LoongArch_REG_R27 = 72,
	LoongArch_REG_R28 = 73,
	LoongArch_REG_R29 = 74,
	LoongArch_REG_R30 = 75,
	LoongArch_REG_R31 = 76,
	LoongArch_REG_SCR0 = 77,
	LoongArch_REG_SCR1 = 78,
	LoongArch_REG_SCR2 = 79,
	LoongArch_REG_SCR3 = 80,
	LoongArch_REG_VR0 = 81,
	LoongArch_REG_VR1 = 82,
	LoongArch_REG_VR2 = 83,
	LoongArch_REG_VR3 = 84,
	LoongArch_REG_VR4 = 85,
	LoongArch_REG_VR5 = 86,
	LoongArch_REG_VR6 = 87,
	LoongArch_REG_VR7 = 88,
	LoongArch_REG_VR8 = 89,
	LoongArch_REG_VR9 = 90,
	LoongArch_REG_VR10 = 91,
	LoongArch_REG_VR11 = 92,
	LoongArch_REG_VR12 = 93,
	LoongArch_REG_VR13 = 94,
	LoongArch_REG_VR14 = 95,
	LoongArch_REG_VR15 = 96,
	LoongArch_REG_VR16 = 97,
	LoongArch_REG_VR17 = 98,
	LoongArch_REG_VR18 = 99,
	LoongArch_REG_VR19 = 100,
	LoongArch_REG_VR20 = 101,
	LoongArch_REG_VR21 = 102,
	LoongArch_REG_VR22 = 103,
	LoongArch_REG_VR23 = 104,
	LoongArch_REG_VR24 = 105,
	LoongArch_REG_VR25 = 106,
	LoongArch_REG_VR26 = 107,
	LoongArch_REG_VR27 = 108,
	LoongArch_REG_VR28 = 109,
	LoongArch_REG_VR29 = 110,
	LoongArch_REG_VR30 = 111,
	LoongArch_REG_VR31 = 112,
	LoongArch_REG_XR0 = 113,
	LoongArch_REG_XR1 = 114,
	LoongArch_REG_XR2 = 115,
	LoongArch_REG_XR3 = 116,
	LoongArch_REG_XR4 = 117,
	LoongArch_REG_XR5 = 118,
	LoongArch_REG_XR6 = 119,
	LoongArch_REG_XR7 = 120,
	LoongArch_REG_XR8 = 121,
	LoongArch_REG_XR9 = 122,
	LoongArch_REG_XR10 = 123,
	LoongArch_REG_XR11 = 124,
	LoongArch_REG_XR12 = 125,
	LoongArch_REG_XR13 = 126,
	LoongArch_REG_XR14 = 127,
	LoongArch_REG_XR15 = 128,
	LoongArch_REG_XR16 = 129,
	LoongArch_REG_XR17 = 130,
	LoongArch_REG_XR18 = 131,
	LoongArch_REG_XR19 = 132,
	LoongArch_REG_XR20 = 133,
	LoongArch_REG_XR21 = 134,
	LoongArch_REG_XR22 = 135,
	LoongArch_REG_XR23 = 136,
	LoongArch_REG_XR24 = 137,
	LoongArch_REG_XR25 = 138,
	LoongArch_REG_XR26 = 139,
	LoongArch_REG_XR27 = 140,
	LoongArch_REG_XR28 = 141,
	LoongArch_REG_XR29 = 142,
	LoongArch_REG_XR30 = 143,
	LoongArch_REG_XR31 = 144,
	LoongArch_REG_F0_64 = 145,
	LoongArch_REG_F1_64 = 146,
	LoongArch_REG_F2_64 = 147,
	LoongArch_REG_F3_64 = 148,
	LoongArch_REG_F4_64 = 149,
	LoongArch_REG_F5_64 = 150,
	LoongArch_REG_F6_64 = 151,
	LoongArch_REG_F7_64 = 152,
	LoongArch_REG_F8_64 = 153,
	LoongArch_REG_F9_64 = 154,
	LoongArch_REG_F10_64 = 155,
	LoongArch_REG_F11_64 = 156,
	LoongArch_REG_F12_64 = 157,
	LoongArch_REG_F13_64 = 158,
	LoongArch_REG_F14_64 = 159,
	LoongArch_REG_F15_64 = 160,
	LoongArch_REG_F16_64 = 161,
	LoongArch_REG_F17_64 = 162,
	LoongArch_REG_F18_64 = 163,
	LoongArch_REG_F19_64 = 164,
	LoongArch_REG_F20_64 = 165,
	LoongArch_REG_F21_64 = 166,
	LoongArch_REG_F22_64 = 167,
	LoongArch_REG_F23_64 = 168,
	LoongArch_REG_F24_64 = 169,
	LoongArch_REG_F25_64 = 170,
	LoongArch_REG_F26_64 = 171,
	LoongArch_REG_F27_64 = 172,
	LoongArch_REG_F28_64 = 173,
	LoongArch_REG_F29_64 = 174,
	LoongArch_REG_F30_64 = 175,
	LoongArch_REG_F31_64 = 176,
	LoongArch_REG_ENDING, // 177

	// clang-format on
	// generated content <LoongArchGenCSRegEnum.inc> end

	// alias registers
	LoongArch_REG_ZERO = LoongArch_REG_R0,
	LoongArch_REG_RA = LoongArch_REG_R1,
	LoongArch_REG_TP = LoongArch_REG_R2,
	LoongArch_REG_SP = LoongArch_REG_R3,
	LoongArch_REG_A0 = LoongArch_REG_R4,
	LoongArch_REG_A1 = LoongArch_REG_R5,
	LoongArch_REG_A2 = LoongArch_REG_R6,
	LoongArch_REG_A3 = LoongArch_REG_R7,
	LoongArch_REG_A4 = LoongArch_REG_R8,
	LoongArch_REG_A5 = LoongArch_REG_R9,
	LoongArch_REG_A6 = LoongArch_REG_R10,
	LoongArch_REG_A7 = LoongArch_REG_R11,
	LoongArch_REG_T0 = LoongArch_REG_R12,
	LoongArch_REG_T1 = LoongArch_REG_R13,
	LoongArch_REG_T2 = LoongArch_REG_R14,
	LoongArch_REG_T3 = LoongArch_REG_R15,
	LoongArch_REG_T4 = LoongArch_REG_R16,
	LoongArch_REG_T5 = LoongArch_REG_R17,
	LoongArch_REG_T6 = LoongArch_REG_R18,
	LoongArch_REG_T7 = LoongArch_REG_R19,
	LoongArch_REG_T8 = LoongArch_REG_R20,
	LoongArch_REG_FP = LoongArch_REG_R22,
	LoongArch_REG_S9 = LoongArch_REG_R22,
	LoongArch_REG_S0 = LoongArch_REG_R23,
	LoongArch_REG_S1 = LoongArch_REG_R24,
	LoongArch_REG_S2 = LoongArch_REG_R25,
	LoongArch_REG_S3 = LoongArch_REG_R26,
	LoongArch_REG_S4 = LoongArch_REG_R27,
	LoongArch_REG_S5 = LoongArch_REG_R28,
	LoongArch_REG_S6 = LoongArch_REG_R29,
	LoongArch_REG_S7 = LoongArch_REG_R30,
	LoongArch_REG_S8 = LoongArch_REG_R31,
} loongarch_reg;

/// LoongArch instruction
typedef enum loongarch_insn {
	// generated content <LoongArchGenCSInsnEnum.inc> begin
	// clang-format off

  LoongArch_INS_INVALID,
	LoongArch_INS_CALL36,
	LoongArch_INS_LA_ABS,
	LoongArch_INS_LA_GOT,
	LoongArch_INS_LA_PCREL,
	LoongArch_INS_LA_TLS_GD,
	LoongArch_INS_LA_TLS_IE,
	LoongArch_INS_LA_TLS_LD,
	LoongArch_INS_LA_TLS_LE,
	LoongArch_INS_LI_D,
	LoongArch_INS_LI_W,
	LoongArch_INS_TAIL36,
	LoongArch_INS_VREPLI_B,
	LoongArch_INS_VREPLI_D,
	LoongArch_INS_VREPLI_H,
	LoongArch_INS_VREPLI_W,
	LoongArch_INS_XVREPLI_B,
	LoongArch_INS_XVREPLI_D,
	LoongArch_INS_XVREPLI_H,
	LoongArch_INS_XVREPLI_W,
	LoongArch_INS_ADC_B,
	LoongArch_INS_ADC_D,
	LoongArch_INS_ADC_H,
	LoongArch_INS_ADC_W,
	LoongArch_INS_ADDI_D,
	LoongArch_INS_ADDI_W,
	LoongArch_INS_ADDU12I_D,
	LoongArch_INS_ADDU12I_W,
	LoongArch_INS_ADDU16I_D,
	LoongArch_INS_ADD_D,
	LoongArch_INS_ADD_W,
	LoongArch_INS_ALSL_D,
	LoongArch_INS_ALSL_W,
	LoongArch_INS_ALSL_WU,
	LoongArch_INS_AMADD_B,
	LoongArch_INS_AMADD_D,
	LoongArch_INS_AMADD_H,
	LoongArch_INS_AMADD_W,
	LoongArch_INS_AMADD_DB_B,
	LoongArch_INS_AMADD_DB_D,
	LoongArch_INS_AMADD_DB_H,
	LoongArch_INS_AMADD_DB_W,
	LoongArch_INS_AMAND_D,
	LoongArch_INS_AMAND_W,
	LoongArch_INS_AMAND_DB_D,
	LoongArch_INS_AMAND_DB_W,
	LoongArch_INS_AMCAS_B,
	LoongArch_INS_AMCAS_D,
	LoongArch_INS_AMCAS_H,
	LoongArch_INS_AMCAS_W,
	LoongArch_INS_AMCAS_DB_B,
	LoongArch_INS_AMCAS_DB_D,
	LoongArch_INS_AMCAS_DB_H,
	LoongArch_INS_AMCAS_DB_W,
	LoongArch_INS_AMMAX_D,
	LoongArch_INS_AMMAX_DU,
	LoongArch_INS_AMMAX_W,
	LoongArch_INS_AMMAX_WU,
	LoongArch_INS_AMMAX_DB_D,
	LoongArch_INS_AMMAX_DB_DU,
	LoongArch_INS_AMMAX_DB_W,
	LoongArch_INS_AMMAX_DB_WU,
	LoongArch_INS_AMMIN_D,
	LoongArch_INS_AMMIN_DU,
	LoongArch_INS_AMMIN_W,
	LoongArch_INS_AMMIN_WU,
	LoongArch_INS_AMMIN_DB_D,
	LoongArch_INS_AMMIN_DB_DU,
	LoongArch_INS_AMMIN_DB_W,
	LoongArch_INS_AMMIN_DB_WU,
	LoongArch_INS_AMOR_D,
	LoongArch_INS_AMOR_W,
	LoongArch_INS_AMOR_DB_D,
	LoongArch_INS_AMOR_DB_W,
	LoongArch_INS_AMSWAP_B,
	LoongArch_INS_AMSWAP_D,
	LoongArch_INS_AMSWAP_H,
	LoongArch_INS_AMSWAP_W,
	LoongArch_INS_AMSWAP_DB_B,
	LoongArch_INS_AMSWAP_DB_D,
	LoongArch_INS_AMSWAP_DB_H,
	LoongArch_INS_AMSWAP_DB_W,
	LoongArch_INS_AMXOR_D,
	LoongArch_INS_AMXOR_W,
	LoongArch_INS_AMXOR_DB_D,
	LoongArch_INS_AMXOR_DB_W,
	LoongArch_INS_AND,
	LoongArch_INS_ANDI,
	LoongArch_INS_ANDN,
	LoongArch_INS_ARMADC_W,
	LoongArch_INS_ARMADD_W,
	LoongArch_INS_ARMAND_W,
	LoongArch_INS_ARMMFFLAG,
	LoongArch_INS_ARMMOVE,
	LoongArch_INS_ARMMOV_D,
	LoongArch_INS_ARMMOV_W,
	LoongArch_INS_ARMMTFLAG,
	LoongArch_INS_ARMNOT_W,
	LoongArch_INS_ARMOR_W,
	LoongArch_INS_ARMROTRI_W,
	LoongArch_INS_ARMROTR_W,
	LoongArch_INS_ARMRRX_W,
	LoongArch_INS_ARMSBC_W,
	LoongArch_INS_ARMSLLI_W,
	LoongArch_INS_ARMSLL_W,
	LoongArch_INS_ARMSRAI_W,
	LoongArch_INS_ARMSRA_W,
	LoongArch_INS_ARMSRLI_W,
	LoongArch_INS_ARMSRL_W,
	LoongArch_INS_ARMSUB_W,
	LoongArch_INS_ARMXOR_W,
	LoongArch_INS_ASRTGT_D,
	LoongArch_INS_ASRTLE_D,
	LoongArch_INS_B,
	LoongArch_INS_BCEQZ,
	LoongArch_INS_BCNEZ,
	LoongArch_INS_BEQ,
	LoongArch_INS_BEQZ,
	LoongArch_INS_BGE,
	LoongArch_INS_BGEU,
	LoongArch_INS_BITREV_4B,
	LoongArch_INS_BITREV_8B,
	LoongArch_INS_BITREV_D,
	LoongArch_INS_BITREV_W,
	LoongArch_INS_BL,
	LoongArch_INS_BLT,
	LoongArch_INS_BLTU,
	LoongArch_INS_BNE,
	LoongArch_INS_BNEZ,
	LoongArch_INS_BREAK,
	LoongArch_INS_BSTRINS_D,
	LoongArch_INS_BSTRINS_W,
	LoongArch_INS_BSTRPICK_D,
	LoongArch_INS_BSTRPICK_W,
	LoongArch_INS_BYTEPICK_D,
	LoongArch_INS_BYTEPICK_W,
	LoongArch_INS_CACOP,
	LoongArch_INS_CLO_D,
	LoongArch_INS_CLO_W,
	LoongArch_INS_CLZ_D,
	LoongArch_INS_CLZ_W,
	LoongArch_INS_CPUCFG,
	LoongArch_INS_CRCC_W_B_W,
	LoongArch_INS_CRCC_W_D_W,
	LoongArch_INS_CRCC_W_H_W,
	LoongArch_INS_CRCC_W_W_W,
	LoongArch_INS_CRC_W_B_W,
	LoongArch_INS_CRC_W_D_W,
	LoongArch_INS_CRC_W_H_W,
	LoongArch_INS_CRC_W_W_W,
	LoongArch_INS_CSRRD,
	LoongArch_INS_CSRWR,
	LoongArch_INS_CSRXCHG,
	LoongArch_INS_CTO_D,
	LoongArch_INS_CTO_W,
	LoongArch_INS_CTZ_D,
	LoongArch_INS_CTZ_W,
	LoongArch_INS_DBAR,
	LoongArch_INS_DBCL,
	LoongArch_INS_DIV_D,
	LoongArch_INS_DIV_DU,
	LoongArch_INS_DIV_W,
	LoongArch_INS_DIV_WU,
	LoongArch_INS_ERTN,
	LoongArch_INS_EXT_W_B,
	LoongArch_INS_EXT_W_H,
	LoongArch_INS_FABS_D,
	LoongArch_INS_FABS_S,
	LoongArch_INS_FADD_D,
	LoongArch_INS_FADD_S,
	LoongArch_INS_FCLASS_D,
	LoongArch_INS_FCLASS_S,
	LoongArch_INS_FCMP_CAF_D,
	LoongArch_INS_FCMP_CAF_S,
	LoongArch_INS_FCMP_CEQ_D,
	LoongArch_INS_FCMP_CEQ_S,
	LoongArch_INS_FCMP_CLE_D,
	LoongArch_INS_FCMP_CLE_S,
	LoongArch_INS_FCMP_CLT_D,
	LoongArch_INS_FCMP_CLT_S,
	LoongArch_INS_FCMP_CNE_D,
	LoongArch_INS_FCMP_CNE_S,
	LoongArch_INS_FCMP_COR_D,
	LoongArch_INS_FCMP_COR_S,
	LoongArch_INS_FCMP_CUEQ_D,
	LoongArch_INS_FCMP_CUEQ_S,
	LoongArch_INS_FCMP_CULE_D,
	LoongArch_INS_FCMP_CULE_S,
	LoongArch_INS_FCMP_CULT_D,
	LoongArch_INS_FCMP_CULT_S,
	LoongArch_INS_FCMP_CUNE_D,
	LoongArch_INS_FCMP_CUNE_S,
	LoongArch_INS_FCMP_CUN_D,
	LoongArch_INS_FCMP_CUN_S,
	LoongArch_INS_FCMP_SAF_D,
	LoongArch_INS_FCMP_SAF_S,
	LoongArch_INS_FCMP_SEQ_D,
	LoongArch_INS_FCMP_SEQ_S,
	LoongArch_INS_FCMP_SLE_D,
	LoongArch_INS_FCMP_SLE_S,
	LoongArch_INS_FCMP_SLT_D,
	LoongArch_INS_FCMP_SLT_S,
	LoongArch_INS_FCMP_SNE_D,
	LoongArch_INS_FCMP_SNE_S,
	LoongArch_INS_FCMP_SOR_D,
	LoongArch_INS_FCMP_SOR_S,
	LoongArch_INS_FCMP_SUEQ_D,
	LoongArch_INS_FCMP_SUEQ_S,
	LoongArch_INS_FCMP_SULE_D,
	LoongArch_INS_FCMP_SULE_S,
	LoongArch_INS_FCMP_SULT_D,
	LoongArch_INS_FCMP_SULT_S,
	LoongArch_INS_FCMP_SUNE_D,
	LoongArch_INS_FCMP_SUNE_S,
	LoongArch_INS_FCMP_SUN_D,
	LoongArch_INS_FCMP_SUN_S,
	LoongArch_INS_FCOPYSIGN_D,
	LoongArch_INS_FCOPYSIGN_S,
	LoongArch_INS_FCVT_D_LD,
	LoongArch_INS_FCVT_D_S,
	LoongArch_INS_FCVT_LD_D,
	LoongArch_INS_FCVT_S_D,
	LoongArch_INS_FCVT_UD_D,
	LoongArch_INS_FDIV_D,
	LoongArch_INS_FDIV_S,
	LoongArch_INS_FFINT_D_L,
	LoongArch_INS_FFINT_D_W,
	LoongArch_INS_FFINT_S_L,
	LoongArch_INS_FFINT_S_W,
	LoongArch_INS_FLDGT_D,
	LoongArch_INS_FLDGT_S,
	LoongArch_INS_FLDLE_D,
	LoongArch_INS_FLDLE_S,
	LoongArch_INS_FLDX_D,
	LoongArch_INS_FLDX_S,
	LoongArch_INS_FLD_D,
	LoongArch_INS_FLD_S,
	LoongArch_INS_FLOGB_D,
	LoongArch_INS_FLOGB_S,
	LoongArch_INS_FMADD_D,
	LoongArch_INS_FMADD_S,
	LoongArch_INS_FMAXA_D,
	LoongArch_INS_FMAXA_S,
	LoongArch_INS_FMAX_D,
	LoongArch_INS_FMAX_S,
	LoongArch_INS_FMINA_D,
	LoongArch_INS_FMINA_S,
	LoongArch_INS_FMIN_D,
	LoongArch_INS_FMIN_S,
	LoongArch_INS_FMOV_D,
	LoongArch_INS_FMOV_S,
	LoongArch_INS_FMSUB_D,
	LoongArch_INS_FMSUB_S,
	LoongArch_INS_FMUL_D,
	LoongArch_INS_FMUL_S,
	LoongArch_INS_FNEG_D,
	LoongArch_INS_FNEG_S,
	LoongArch_INS_FNMADD_D,
	LoongArch_INS_FNMADD_S,
	LoongArch_INS_FNMSUB_D,
	LoongArch_INS_FNMSUB_S,
	LoongArch_INS_FRECIPE_D,
	LoongArch_INS_FRECIPE_S,
	LoongArch_INS_FRECIP_D,
	LoongArch_INS_FRECIP_S,
	LoongArch_INS_FRINT_D,
	LoongArch_INS_FRINT_S,
	LoongArch_INS_FRSQRTE_D,
	LoongArch_INS_FRSQRTE_S,
	LoongArch_INS_FRSQRT_D,
	LoongArch_INS_FRSQRT_S,
	LoongArch_INS_FSCALEB_D,
	LoongArch_INS_FSCALEB_S,
	LoongArch_INS_FSEL,
	LoongArch_INS_FSQRT_D,
	LoongArch_INS_FSQRT_S,
	LoongArch_INS_FSTGT_D,
	LoongArch_INS_FSTGT_S,
	LoongArch_INS_FSTLE_D,
	LoongArch_INS_FSTLE_S,
	LoongArch_INS_FSTX_D,
	LoongArch_INS_FSTX_S,
	LoongArch_INS_FST_D,
	LoongArch_INS_FST_S,
	LoongArch_INS_FSUB_D,
	LoongArch_INS_FSUB_S,
	LoongArch_INS_FTINTRM_L_D,
	LoongArch_INS_FTINTRM_L_S,
	LoongArch_INS_FTINTRM_W_D,
	LoongArch_INS_FTINTRM_W_S,
	LoongArch_INS_FTINTRNE_L_D,
	LoongArch_INS_FTINTRNE_L_S,
	LoongArch_INS_FTINTRNE_W_D,
	LoongArch_INS_FTINTRNE_W_S,
	LoongArch_INS_FTINTRP_L_D,
	LoongArch_INS_FTINTRP_L_S,
	LoongArch_INS_FTINTRP_W_D,
	LoongArch_INS_FTINTRP_W_S,
	LoongArch_INS_FTINTRZ_L_D,
	LoongArch_INS_FTINTRZ_L_S,
	LoongArch_INS_FTINTRZ_W_D,
	LoongArch_INS_FTINTRZ_W_S,
	LoongArch_INS_FTINT_L_D,
	LoongArch_INS_FTINT_L_S,
	LoongArch_INS_FTINT_W_D,
	LoongArch_INS_FTINT_W_S,
	LoongArch_INS_GCSRRD,
	LoongArch_INS_GCSRWR,
	LoongArch_INS_GCSRXCHG,
	LoongArch_INS_GTLBFLUSH,
	LoongArch_INS_HVCL,
	LoongArch_INS_IBAR,
	LoongArch_INS_IDLE,
	LoongArch_INS_INVTLB,
	LoongArch_INS_IOCSRRD_B,
	LoongArch_INS_IOCSRRD_D,
	LoongArch_INS_IOCSRRD_H,
	LoongArch_INS_IOCSRRD_W,
	LoongArch_INS_IOCSRWR_B,
	LoongArch_INS_IOCSRWR_D,
	LoongArch_INS_IOCSRWR_H,
	LoongArch_INS_IOCSRWR_W,
	LoongArch_INS_JIRL,
	LoongArch_INS_JISCR0,
	LoongArch_INS_JISCR1,
	LoongArch_INS_LDDIR,
	LoongArch_INS_LDGT_B,
	LoongArch_INS_LDGT_D,
	LoongArch_INS_LDGT_H,
	LoongArch_INS_LDGT_W,
	LoongArch_INS_LDLE_B,
	LoongArch_INS_LDLE_D,
	LoongArch_INS_LDLE_H,
	LoongArch_INS_LDLE_W,
	LoongArch_INS_LDL_D,
	LoongArch_INS_LDL_W,
	LoongArch_INS_LDPTE,
	LoongArch_INS_LDPTR_D,
	LoongArch_INS_LDPTR_W,
	LoongArch_INS_LDR_D,
	LoongArch_INS_LDR_W,
	LoongArch_INS_LDX_B,
	LoongArch_INS_LDX_BU,
	LoongArch_INS_LDX_D,
	LoongArch_INS_LDX_H,
	LoongArch_INS_LDX_HU,
	LoongArch_INS_LDX_W,
	LoongArch_INS_LDX_WU,
	LoongArch_INS_LD_B,
	LoongArch_INS_LD_BU,
	LoongArch_INS_LD_D,
	LoongArch_INS_LD_H,
	LoongArch_INS_LD_HU,
	LoongArch_INS_LD_W,
	LoongArch_INS_LD_WU,
	LoongArch_INS_LLACQ_D,
	LoongArch_INS_LLACQ_W,
	LoongArch_INS_LL_D,
	LoongArch_INS_LL_W,
	LoongArch_INS_LU12I_W,
	LoongArch_INS_LU32I_D,
	LoongArch_INS_LU52I_D,
	LoongArch_INS_MASKEQZ,
	LoongArch_INS_MASKNEZ,
	LoongArch_INS_MOD_D,
	LoongArch_INS_MOD_DU,
	LoongArch_INS_MOD_W,
	LoongArch_INS_MOD_WU,
	LoongArch_INS_MOVCF2FR,
	LoongArch_INS_MOVCF2GR,
	LoongArch_INS_MOVFCSR2GR,
	LoongArch_INS_MOVFR2CF,
	LoongArch_INS_MOVFR2GR_D,
	LoongArch_INS_MOVFR2GR_S,
	LoongArch_INS_MOVFRH2GR_S,
	LoongArch_INS_MOVGR2CF,
	LoongArch_INS_MOVGR2FCSR,
	LoongArch_INS_MOVGR2FRH_W,
	LoongArch_INS_MOVGR2FR_D,
	LoongArch_INS_MOVGR2FR_W,
	LoongArch_INS_MOVGR2SCR,
	LoongArch_INS_MOVSCR2GR,
	LoongArch_INS_MULH_D,
	LoongArch_INS_MULH_DU,
	LoongArch_INS_MULH_W,
	LoongArch_INS_MULH_WU,
	LoongArch_INS_MULW_D_W,
	LoongArch_INS_MULW_D_WU,
	LoongArch_INS_MUL_D,
	LoongArch_INS_MUL_W,
	LoongArch_INS_NOR,
	LoongArch_INS_OR,
	LoongArch_INS_ORI,
	LoongArch_INS_ORN,
	LoongArch_INS_PCADDI,
	LoongArch_INS_PCADDU12I,
	LoongArch_INS_PCADDU18I,
	LoongArch_INS_PCALAU12I,
	LoongArch_INS_PRELD,
	LoongArch_INS_PRELDX,
	LoongArch_INS_RCRI_B,
	LoongArch_INS_RCRI_D,
	LoongArch_INS_RCRI_H,
	LoongArch_INS_RCRI_W,
	LoongArch_INS_RCR_B,
	LoongArch_INS_RCR_D,
	LoongArch_INS_RCR_H,
	LoongArch_INS_RCR_W,
	LoongArch_INS_RDTIMEH_W,
	LoongArch_INS_RDTIMEL_W,
	LoongArch_INS_RDTIME_D,
	LoongArch_INS_REVB_2H,
	LoongArch_INS_REVB_2W,
	LoongArch_INS_REVB_4H,
	LoongArch_INS_REVB_D,
	LoongArch_INS_REVH_2W,
	LoongArch_INS_REVH_D,
	LoongArch_INS_ROTRI_B,
	LoongArch_INS_ROTRI_D,
	LoongArch_INS_ROTRI_H,
	LoongArch_INS_ROTRI_W,
	LoongArch_INS_ROTR_B,
	LoongArch_INS_ROTR_D,
	LoongArch_INS_ROTR_H,
	LoongArch_INS_ROTR_W,
	LoongArch_INS_SBC_B,
	LoongArch_INS_SBC_D,
	LoongArch_INS_SBC_H,
	LoongArch_INS_SBC_W,
	LoongArch_INS_SCREL_D,
	LoongArch_INS_SCREL_W,
	LoongArch_INS_SC_D,
	LoongArch_INS_SC_Q,
	LoongArch_INS_SC_W,
	LoongArch_INS_SETARMJ,
	LoongArch_INS_SETX86J,
	LoongArch_INS_SETX86LOOPE,
	LoongArch_INS_SETX86LOOPNE,
	LoongArch_INS_SLLI_D,
	LoongArch_INS_SLLI_W,
	LoongArch_INS_SLL_D,
	LoongArch_INS_SLL_W,
	LoongArch_INS_SLT,
	LoongArch_INS_SLTI,
	LoongArch_INS_SLTU,
	LoongArch_INS_SLTUI,
	LoongArch_INS_SRAI_D,
	LoongArch_INS_SRAI_W,
	LoongArch_INS_SRA_D,
	LoongArch_INS_SRA_W,
	LoongArch_INS_SRLI_D,
	LoongArch_INS_SRLI_W,
	LoongArch_INS_SRL_D,
	LoongArch_INS_SRL_W,
	LoongArch_INS_STGT_B,
	LoongArch_INS_STGT_D,
	LoongArch_INS_STGT_H,
	LoongArch_INS_STGT_W,
	LoongArch_INS_STLE_B,
	LoongArch_INS_STLE_D,
	LoongArch_INS_STLE_H,
	LoongArch_INS_STLE_W,
	LoongArch_INS_STL_D,
	LoongArch_INS_STL_W,
	LoongArch_INS_STPTR_D,
	LoongArch_INS_STPTR_W,
	LoongArch_INS_STR_D,
	LoongArch_INS_STR_W,
	LoongArch_INS_STX_B,
	LoongArch_INS_STX_D,
	LoongArch_INS_STX_H,
	LoongArch_INS_STX_W,
	LoongArch_INS_ST_B,
	LoongArch_INS_ST_D,
	LoongArch_INS_ST_H,
	LoongArch_INS_ST_W,
	LoongArch_INS_SUB_D,
	LoongArch_INS_SUB_W,
	LoongArch_INS_SYSCALL,
	LoongArch_INS_TLBCLR,
	LoongArch_INS_TLBFILL,
	LoongArch_INS_TLBFLUSH,
	LoongArch_INS_TLBRD,
	LoongArch_INS_TLBSRCH,
	LoongArch_INS_TLBWR,
	LoongArch_INS_VABSD_B,
	LoongArch_INS_VABSD_BU,
	LoongArch_INS_VABSD_D,
	LoongArch_INS_VABSD_DU,
	LoongArch_INS_VABSD_H,
	LoongArch_INS_VABSD_HU,
	LoongArch_INS_VABSD_W,
	LoongArch_INS_VABSD_WU,
	LoongArch_INS_VADDA_B,
	LoongArch_INS_VADDA_D,
	LoongArch_INS_VADDA_H,
	LoongArch_INS_VADDA_W,
	LoongArch_INS_VADDI_BU,
	LoongArch_INS_VADDI_DU,
	LoongArch_INS_VADDI_HU,
	LoongArch_INS_VADDI_WU,
	LoongArch_INS_VADDWEV_D_W,
	LoongArch_INS_VADDWEV_D_WU,
	LoongArch_INS_VADDWEV_D_WU_W,
	LoongArch_INS_VADDWEV_H_B,
	LoongArch_INS_VADDWEV_H_BU,
	LoongArch_INS_VADDWEV_H_BU_B,
	LoongArch_INS_VADDWEV_Q_D,
	LoongArch_INS_VADDWEV_Q_DU,
	LoongArch_INS_VADDWEV_Q_DU_D,
	LoongArch_INS_VADDWEV_W_H,
	LoongArch_INS_VADDWEV_W_HU,
	LoongArch_INS_VADDWEV_W_HU_H,
	LoongArch_INS_VADDWOD_D_W,
	LoongArch_INS_VADDWOD_D_WU,
	LoongArch_INS_VADDWOD_D_WU_W,
	LoongArch_INS_VADDWOD_H_B,
	LoongArch_INS_VADDWOD_H_BU,
	LoongArch_INS_VADDWOD_H_BU_B,
	LoongArch_INS_VADDWOD_Q_D,
	LoongArch_INS_VADDWOD_Q_DU,
	LoongArch_INS_VADDWOD_Q_DU_D,
	LoongArch_INS_VADDWOD_W_H,
	LoongArch_INS_VADDWOD_W_HU,
	LoongArch_INS_VADDWOD_W_HU_H,
	LoongArch_INS_VADD_B,
	LoongArch_INS_VADD_D,
	LoongArch_INS_VADD_H,
	LoongArch_INS_VADD_Q,
	LoongArch_INS_VADD_W,
	LoongArch_INS_VANDI_B,
	LoongArch_INS_VANDN_V,
	LoongArch_INS_VAND_V,
	LoongArch_INS_VAVGR_B,
	LoongArch_INS_VAVGR_BU,
	LoongArch_INS_VAVGR_D,
	LoongArch_INS_VAVGR_DU,
	LoongArch_INS_VAVGR_H,
	LoongArch_INS_VAVGR_HU,
	LoongArch_INS_VAVGR_W,
	LoongArch_INS_VAVGR_WU,
	LoongArch_INS_VAVG_B,
	LoongArch_INS_VAVG_BU,
	LoongArch_INS_VAVG_D,
	LoongArch_INS_VAVG_DU,
	LoongArch_INS_VAVG_H,
	LoongArch_INS_VAVG_HU,
	LoongArch_INS_VAVG_W,
	LoongArch_INS_VAVG_WU,
	LoongArch_INS_VBITCLRI_B,
	LoongArch_INS_VBITCLRI_D,
	LoongArch_INS_VBITCLRI_H,
	LoongArch_INS_VBITCLRI_W,
	LoongArch_INS_VBITCLR_B,
	LoongArch_INS_VBITCLR_D,
	LoongArch_INS_VBITCLR_H,
	LoongArch_INS_VBITCLR_W,
	LoongArch_INS_VBITREVI_B,
	LoongArch_INS_VBITREVI_D,
	LoongArch_INS_VBITREVI_H,
	LoongArch_INS_VBITREVI_W,
	LoongArch_INS_VBITREV_B,
	LoongArch_INS_VBITREV_D,
	LoongArch_INS_VBITREV_H,
	LoongArch_INS_VBITREV_W,
	LoongArch_INS_VBITSELI_B,
	LoongArch_INS_VBITSEL_V,
	LoongArch_INS_VBITSETI_B,
	LoongArch_INS_VBITSETI_D,
	LoongArch_INS_VBITSETI_H,
	LoongArch_INS_VBITSETI_W,
	LoongArch_INS_VBITSET_B,
	LoongArch_INS_VBITSET_D,
	LoongArch_INS_VBITSET_H,
	LoongArch_INS_VBITSET_W,
	LoongArch_INS_VBSLL_V,
	LoongArch_INS_VBSRL_V,
	LoongArch_INS_VCLO_B,
	LoongArch_INS_VCLO_D,
	LoongArch_INS_VCLO_H,
	LoongArch_INS_VCLO_W,
	LoongArch_INS_VCLZ_B,
	LoongArch_INS_VCLZ_D,
	LoongArch_INS_VCLZ_H,
	LoongArch_INS_VCLZ_W,
	LoongArch_INS_VDIV_B,
	LoongArch_INS_VDIV_BU,
	LoongArch_INS_VDIV_D,
	LoongArch_INS_VDIV_DU,
	LoongArch_INS_VDIV_H,
	LoongArch_INS_VDIV_HU,
	LoongArch_INS_VDIV_W,
	LoongArch_INS_VDIV_WU,
	LoongArch_INS_VEXT2XV_DU_BU,
	LoongArch_INS_VEXT2XV_DU_HU,
	LoongArch_INS_VEXT2XV_DU_WU,
	LoongArch_INS_VEXT2XV_D_B,
	LoongArch_INS_VEXT2XV_D_H,
	LoongArch_INS_VEXT2XV_D_W,
	LoongArch_INS_VEXT2XV_HU_BU,
	LoongArch_INS_VEXT2XV_H_B,
	LoongArch_INS_VEXT2XV_WU_BU,
	LoongArch_INS_VEXT2XV_WU_HU,
	LoongArch_INS_VEXT2XV_W_B,
	LoongArch_INS_VEXT2XV_W_H,
	LoongArch_INS_VEXTH_DU_WU,
	LoongArch_INS_VEXTH_D_W,
	LoongArch_INS_VEXTH_HU_BU,
	LoongArch_INS_VEXTH_H_B,
	LoongArch_INS_VEXTH_QU_DU,
	LoongArch_INS_VEXTH_Q_D,
	LoongArch_INS_VEXTH_WU_HU,
	LoongArch_INS_VEXTH_W_H,
	LoongArch_INS_VEXTL_QU_DU,
	LoongArch_INS_VEXTL_Q_D,
	LoongArch_INS_VEXTRINS_B,
	LoongArch_INS_VEXTRINS_D,
	LoongArch_INS_VEXTRINS_H,
	LoongArch_INS_VEXTRINS_W,
	LoongArch_INS_VFADD_D,
	LoongArch_INS_VFADD_S,
	LoongArch_INS_VFCLASS_D,
	LoongArch_INS_VFCLASS_S,
	LoongArch_INS_VFCMP_CAF_D,
	LoongArch_INS_VFCMP_CAF_S,
	LoongArch_INS_VFCMP_CEQ_D,
	LoongArch_INS_VFCMP_CEQ_S,
	LoongArch_INS_VFCMP_CLE_D,
	LoongArch_INS_VFCMP_CLE_S,
	LoongArch_INS_VFCMP_CLT_D,
	LoongArch_INS_VFCMP_CLT_S,
	LoongArch_INS_VFCMP_CNE_D,
	LoongArch_INS_VFCMP_CNE_S,
	LoongArch_INS_VFCMP_COR_D,
	LoongArch_INS_VFCMP_COR_S,
	LoongArch_INS_VFCMP_CUEQ_D,
	LoongArch_INS_VFCMP_CUEQ_S,
	LoongArch_INS_VFCMP_CULE_D,
	LoongArch_INS_VFCMP_CULE_S,
	LoongArch_INS_VFCMP_CULT_D,
	LoongArch_INS_VFCMP_CULT_S,
	LoongArch_INS_VFCMP_CUNE_D,
	LoongArch_INS_VFCMP_CUNE_S,
	LoongArch_INS_VFCMP_CUN_D,
	LoongArch_INS_VFCMP_CUN_S,
	LoongArch_INS_VFCMP_SAF_D,
	LoongArch_INS_VFCMP_SAF_S,
	LoongArch_INS_VFCMP_SEQ_D,
	LoongArch_INS_VFCMP_SEQ_S,
	LoongArch_INS_VFCMP_SLE_D,
	LoongArch_INS_VFCMP_SLE_S,
	LoongArch_INS_VFCMP_SLT_D,
	LoongArch_INS_VFCMP_SLT_S,
	LoongArch_INS_VFCMP_SNE_D,
	LoongArch_INS_VFCMP_SNE_S,
	LoongArch_INS_VFCMP_SOR_D,
	LoongArch_INS_VFCMP_SOR_S,
	LoongArch_INS_VFCMP_SUEQ_D,
	LoongArch_INS_VFCMP_SUEQ_S,
	LoongArch_INS_VFCMP_SULE_D,
	LoongArch_INS_VFCMP_SULE_S,
	LoongArch_INS_VFCMP_SULT_D,
	LoongArch_INS_VFCMP_SULT_S,
	LoongArch_INS_VFCMP_SUNE_D,
	LoongArch_INS_VFCMP_SUNE_S,
	LoongArch_INS_VFCMP_SUN_D,
	LoongArch_INS_VFCMP_SUN_S,
	LoongArch_INS_VFCVTH_D_S,
	LoongArch_INS_VFCVTH_S_H,
	LoongArch_INS_VFCVTL_D_S,
	LoongArch_INS_VFCVTL_S_H,
	LoongArch_INS_VFCVT_H_S,
	LoongArch_INS_VFCVT_S_D,
	LoongArch_INS_VFDIV_D,
	LoongArch_INS_VFDIV_S,
	LoongArch_INS_VFFINTH_D_W,
	LoongArch_INS_VFFINTL_D_W,
	LoongArch_INS_VFFINT_D_L,
	LoongArch_INS_VFFINT_D_LU,
	LoongArch_INS_VFFINT_S_L,
	LoongArch_INS_VFFINT_S_W,
	LoongArch_INS_VFFINT_S_WU,
	LoongArch_INS_VFLOGB_D,
	LoongArch_INS_VFLOGB_S,
	LoongArch_INS_VFMADD_D,
	LoongArch_INS_VFMADD_S,
	LoongArch_INS_VFMAXA_D,
	LoongArch_INS_VFMAXA_S,
	LoongArch_INS_VFMAX_D,
	LoongArch_INS_VFMAX_S,
	LoongArch_INS_VFMINA_D,
	LoongArch_INS_VFMINA_S,
	LoongArch_INS_VFMIN_D,
	LoongArch_INS_VFMIN_S,
	LoongArch_INS_VFMSUB_D,
	LoongArch_INS_VFMSUB_S,
	LoongArch_INS_VFMUL_D,
	LoongArch_INS_VFMUL_S,
	LoongArch_INS_VFNMADD_D,
	LoongArch_INS_VFNMADD_S,
	LoongArch_INS_VFNMSUB_D,
	LoongArch_INS_VFNMSUB_S,
	LoongArch_INS_VFRECIPE_D,
	LoongArch_INS_VFRECIPE_S,
	LoongArch_INS_VFRECIP_D,
	LoongArch_INS_VFRECIP_S,
	LoongArch_INS_VFRINTRM_D,
	LoongArch_INS_VFRINTRM_S,
	LoongArch_INS_VFRINTRNE_D,
	LoongArch_INS_VFRINTRNE_S,
	LoongArch_INS_VFRINTRP_D,
	LoongArch_INS_VFRINTRP_S,
	LoongArch_INS_VFRINTRZ_D,
	LoongArch_INS_VFRINTRZ_S,
	LoongArch_INS_VFRINT_D,
	LoongArch_INS_VFRINT_S,
	LoongArch_INS_VFRSQRTE_D,
	LoongArch_INS_VFRSQRTE_S,
	LoongArch_INS_VFRSQRT_D,
	LoongArch_INS_VFRSQRT_S,
	LoongArch_INS_VFRSTPI_B,
	LoongArch_INS_VFRSTPI_H,
	LoongArch_INS_VFRSTP_B,
	LoongArch_INS_VFRSTP_H,
	LoongArch_INS_VFSQRT_D,
	LoongArch_INS_VFSQRT_S,
	LoongArch_INS_VFSUB_D,
	LoongArch_INS_VFSUB_S,
	LoongArch_INS_VFTINTH_L_S,
	LoongArch_INS_VFTINTL_L_S,
	LoongArch_INS_VFTINTRMH_L_S,
	LoongArch_INS_VFTINTRML_L_S,
	LoongArch_INS_VFTINTRM_L_D,
	LoongArch_INS_VFTINTRM_W_D,
	LoongArch_INS_VFTINTRM_W_S,
	LoongArch_INS_VFTINTRNEH_L_S,
	LoongArch_INS_VFTINTRNEL_L_S,
	LoongArch_INS_VFTINTRNE_L_D,
	LoongArch_INS_VFTINTRNE_W_D,
	LoongArch_INS_VFTINTRNE_W_S,
	LoongArch_INS_VFTINTRPH_L_S,
	LoongArch_INS_VFTINTRPL_L_S,
	LoongArch_INS_VFTINTRP_L_D,
	LoongArch_INS_VFTINTRP_W_D,
	LoongArch_INS_VFTINTRP_W_S,
	LoongArch_INS_VFTINTRZH_L_S,
	LoongArch_INS_VFTINTRZL_L_S,
	LoongArch_INS_VFTINTRZ_LU_D,
	LoongArch_INS_VFTINTRZ_L_D,
	LoongArch_INS_VFTINTRZ_WU_S,
	LoongArch_INS_VFTINTRZ_W_D,
	LoongArch_INS_VFTINTRZ_W_S,
	LoongArch_INS_VFTINT_LU_D,
	LoongArch_INS_VFTINT_L_D,
	LoongArch_INS_VFTINT_WU_S,
	LoongArch_INS_VFTINT_W_D,
	LoongArch_INS_VFTINT_W_S,
	LoongArch_INS_VHADDW_DU_WU,
	LoongArch_INS_VHADDW_D_W,
	LoongArch_INS_VHADDW_HU_BU,
	LoongArch_INS_VHADDW_H_B,
	LoongArch_INS_VHADDW_QU_DU,
	LoongArch_INS_VHADDW_Q_D,
	LoongArch_INS_VHADDW_WU_HU,
	LoongArch_INS_VHADDW_W_H,
	LoongArch_INS_VHSUBW_DU_WU,
	LoongArch_INS_VHSUBW_D_W,
	LoongArch_INS_VHSUBW_HU_BU,
	LoongArch_INS_VHSUBW_H_B,
	LoongArch_INS_VHSUBW_QU_DU,
	LoongArch_INS_VHSUBW_Q_D,
	LoongArch_INS_VHSUBW_WU_HU,
	LoongArch_INS_VHSUBW_W_H,
	LoongArch_INS_VILVH_B,
	LoongArch_INS_VILVH_D,
	LoongArch_INS_VILVH_H,
	LoongArch_INS_VILVH_W,
	LoongArch_INS_VILVL_B,
	LoongArch_INS_VILVL_D,
	LoongArch_INS_VILVL_H,
	LoongArch_INS_VILVL_W,
	LoongArch_INS_VINSGR2VR_B,
	LoongArch_INS_VINSGR2VR_D,
	LoongArch_INS_VINSGR2VR_H,
	LoongArch_INS_VINSGR2VR_W,
	LoongArch_INS_VLD,
	LoongArch_INS_VLDI,
	LoongArch_INS_VLDREPL_B,
	LoongArch_INS_VLDREPL_D,
	LoongArch_INS_VLDREPL_H,
	LoongArch_INS_VLDREPL_W,
	LoongArch_INS_VLDX,
	LoongArch_INS_VMADDWEV_D_W,
	LoongArch_INS_VMADDWEV_D_WU,
	LoongArch_INS_VMADDWEV_D_WU_W,
	LoongArch_INS_VMADDWEV_H_B,
	LoongArch_INS_VMADDWEV_H_BU,
	LoongArch_INS_VMADDWEV_H_BU_B,
	LoongArch_INS_VMADDWEV_Q_D,
	LoongArch_INS_VMADDWEV_Q_DU,
	LoongArch_INS_VMADDWEV_Q_DU_D,
	LoongArch_INS_VMADDWEV_W_H,
	LoongArch_INS_VMADDWEV_W_HU,
	LoongArch_INS_VMADDWEV_W_HU_H,
	LoongArch_INS_VMADDWOD_D_W,
	LoongArch_INS_VMADDWOD_D_WU,
	LoongArch_INS_VMADDWOD_D_WU_W,
	LoongArch_INS_VMADDWOD_H_B,
	LoongArch_INS_VMADDWOD_H_BU,
	LoongArch_INS_VMADDWOD_H_BU_B,
	LoongArch_INS_VMADDWOD_Q_D,
	LoongArch_INS_VMADDWOD_Q_DU,
	LoongArch_INS_VMADDWOD_Q_DU_D,
	LoongArch_INS_VMADDWOD_W_H,
	LoongArch_INS_VMADDWOD_W_HU,
	LoongArch_INS_VMADDWOD_W_HU_H,
	LoongArch_INS_VMADD_B,
	LoongArch_INS_VMADD_D,
	LoongArch_INS_VMADD_H,
	LoongArch_INS_VMADD_W,
	LoongArch_INS_VMAXI_B,
	LoongArch_INS_VMAXI_BU,
	LoongArch_INS_VMAXI_D,
	LoongArch_INS_VMAXI_DU,
	LoongArch_INS_VMAXI_H,
	LoongArch_INS_VMAXI_HU,
	LoongArch_INS_VMAXI_W,
	LoongArch_INS_VMAXI_WU,
	LoongArch_INS_VMAX_B,
	LoongArch_INS_VMAX_BU,
	LoongArch_INS_VMAX_D,
	LoongArch_INS_VMAX_DU,
	LoongArch_INS_VMAX_H,
	LoongArch_INS_VMAX_HU,
	LoongArch_INS_VMAX_W,
	LoongArch_INS_VMAX_WU,
	LoongArch_INS_VMINI_B,
	LoongArch_INS_VMINI_BU,
	LoongArch_INS_VMINI_D,
	LoongArch_INS_VMINI_DU,
	LoongArch_INS_VMINI_H,
	LoongArch_INS_VMINI_HU,
	LoongArch_INS_VMINI_W,
	LoongArch_INS_VMINI_WU,
	LoongArch_INS_VMIN_B,
	LoongArch_INS_VMIN_BU,
	LoongArch_INS_VMIN_D,
	LoongArch_INS_VMIN_DU,
	LoongArch_INS_VMIN_H,
	LoongArch_INS_VMIN_HU,
	LoongArch_INS_VMIN_W,
	LoongArch_INS_VMIN_WU,
	LoongArch_INS_VMOD_B,
	LoongArch_INS_VMOD_BU,
	LoongArch_INS_VMOD_D,
	LoongArch_INS_VMOD_DU,
	LoongArch_INS_VMOD_H,
	LoongArch_INS_VMOD_HU,
	LoongArch_INS_VMOD_W,
	LoongArch_INS_VMOD_WU,
	LoongArch_INS_VMSKGEZ_B,
	LoongArch_INS_VMSKLTZ_B,
	LoongArch_INS_VMSKLTZ_D,
	LoongArch_INS_VMSKLTZ_H,
	LoongArch_INS_VMSKLTZ_W,
	LoongArch_INS_VMSKNZ_B,
	LoongArch_INS_VMSUB_B,
	LoongArch_INS_VMSUB_D,
	LoongArch_INS_VMSUB_H,
	LoongArch_INS_VMSUB_W,
	LoongArch_INS_VMUH_B,
	LoongArch_INS_VMUH_BU,
	LoongArch_INS_VMUH_D,
	LoongArch_INS_VMUH_DU,
	LoongArch_INS_VMUH_H,
	LoongArch_INS_VMUH_HU,
	LoongArch_INS_VMUH_W,
	LoongArch_INS_VMUH_WU,
	LoongArch_INS_VMULWEV_D_W,
	LoongArch_INS_VMULWEV_D_WU,
	LoongArch_INS_VMULWEV_D_WU_W,
	LoongArch_INS_VMULWEV_H_B,
	LoongArch_INS_VMULWEV_H_BU,
	LoongArch_INS_VMULWEV_H_BU_B,
	LoongArch_INS_VMULWEV_Q_D,
	LoongArch_INS_VMULWEV_Q_DU,
	LoongArch_INS_VMULWEV_Q_DU_D,
	LoongArch_INS_VMULWEV_W_H,
	LoongArch_INS_VMULWEV_W_HU,
	LoongArch_INS_VMULWEV_W_HU_H,
	LoongArch_INS_VMULWOD_D_W,
	LoongArch_INS_VMULWOD_D_WU,
	LoongArch_INS_VMULWOD_D_WU_W,
	LoongArch_INS_VMULWOD_H_B,
	LoongArch_INS_VMULWOD_H_BU,
	LoongArch_INS_VMULWOD_H_BU_B,
	LoongArch_INS_VMULWOD_Q_D,
	LoongArch_INS_VMULWOD_Q_DU,
	LoongArch_INS_VMULWOD_Q_DU_D,
	LoongArch_INS_VMULWOD_W_H,
	LoongArch_INS_VMULWOD_W_HU,
	LoongArch_INS_VMULWOD_W_HU_H,
	LoongArch_INS_VMUL_B,
	LoongArch_INS_VMUL_D,
	LoongArch_INS_VMUL_H,
	LoongArch_INS_VMUL_W,
	LoongArch_INS_VNEG_B,
	LoongArch_INS_VNEG_D,
	LoongArch_INS_VNEG_H,
	LoongArch_INS_VNEG_W,
	LoongArch_INS_VNORI_B,
	LoongArch_INS_VNOR_V,
	LoongArch_INS_VORI_B,
	LoongArch_INS_VORN_V,
	LoongArch_INS_VOR_V,
	LoongArch_INS_VPACKEV_B,
	LoongArch_INS_VPACKEV_D,
	LoongArch_INS_VPACKEV_H,
	LoongArch_INS_VPACKEV_W,
	LoongArch_INS_VPACKOD_B,
	LoongArch_INS_VPACKOD_D,
	LoongArch_INS_VPACKOD_H,
	LoongArch_INS_VPACKOD_W,
	LoongArch_INS_VPCNT_B,
	LoongArch_INS_VPCNT_D,
	LoongArch_INS_VPCNT_H,
	LoongArch_INS_VPCNT_W,
	LoongArch_INS_VPERMI_W,
	LoongArch_INS_VPICKEV_B,
	LoongArch_INS_VPICKEV_D,
	LoongArch_INS_VPICKEV_H,
	LoongArch_INS_VPICKEV_W,
	LoongArch_INS_VPICKOD_B,
	LoongArch_INS_VPICKOD_D,
	LoongArch_INS_VPICKOD_H,
	LoongArch_INS_VPICKOD_W,
	LoongArch_INS_VPICKVE2GR_B,
	LoongArch_INS_VPICKVE2GR_BU,
	LoongArch_INS_VPICKVE2GR_D,
	LoongArch_INS_VPICKVE2GR_DU,
	LoongArch_INS_VPICKVE2GR_H,
	LoongArch_INS_VPICKVE2GR_HU,
	LoongArch_INS_VPICKVE2GR_W,
	LoongArch_INS_VPICKVE2GR_WU,
	LoongArch_INS_VREPLGR2VR_B,
	LoongArch_INS_VREPLGR2VR_D,
	LoongArch_INS_VREPLGR2VR_H,
	LoongArch_INS_VREPLGR2VR_W,
	LoongArch_INS_VREPLVEI_B,
	LoongArch_INS_VREPLVEI_D,
	LoongArch_INS_VREPLVEI_H,
	LoongArch_INS_VREPLVEI_W,
	LoongArch_INS_VREPLVE_B,
	LoongArch_INS_VREPLVE_D,
	LoongArch_INS_VREPLVE_H,
	LoongArch_INS_VREPLVE_W,
	LoongArch_INS_VROTRI_B,
	LoongArch_INS_VROTRI_D,
	LoongArch_INS_VROTRI_H,
	LoongArch_INS_VROTRI_W,
	LoongArch_INS_VROTR_B,
	LoongArch_INS_VROTR_D,
	LoongArch_INS_VROTR_H,
	LoongArch_INS_VROTR_W,
	LoongArch_INS_VSADD_B,
	LoongArch_INS_VSADD_BU,
	LoongArch_INS_VSADD_D,
	LoongArch_INS_VSADD_DU,
	LoongArch_INS_VSADD_H,
	LoongArch_INS_VSADD_HU,
	LoongArch_INS_VSADD_W,
	LoongArch_INS_VSADD_WU,
	LoongArch_INS_VSAT_B,
	LoongArch_INS_VSAT_BU,
	LoongArch_INS_VSAT_D,
	LoongArch_INS_VSAT_DU,
	LoongArch_INS_VSAT_H,
	LoongArch_INS_VSAT_HU,
	LoongArch_INS_VSAT_W,
	LoongArch_INS_VSAT_WU,
	LoongArch_INS_VSEQI_B,
	LoongArch_INS_VSEQI_D,
	LoongArch_INS_VSEQI_H,
	LoongArch_INS_VSEQI_W,
	LoongArch_INS_VSEQ_B,
	LoongArch_INS_VSEQ_D,
	LoongArch_INS_VSEQ_H,
	LoongArch_INS_VSEQ_W,
	LoongArch_INS_VSETALLNEZ_B,
	LoongArch_INS_VSETALLNEZ_D,
	LoongArch_INS_VSETALLNEZ_H,
	LoongArch_INS_VSETALLNEZ_W,
	LoongArch_INS_VSETANYEQZ_B,
	LoongArch_INS_VSETANYEQZ_D,
	LoongArch_INS_VSETANYEQZ_H,
	LoongArch_INS_VSETANYEQZ_W,
	LoongArch_INS_VSETEQZ_V,
	LoongArch_INS_VSETNEZ_V,
	LoongArch_INS_VSHUF4I_B,
	LoongArch_INS_VSHUF4I_D,
	LoongArch_INS_VSHUF4I_H,
	LoongArch_INS_VSHUF4I_W,
	LoongArch_INS_VSHUF_B,
	LoongArch_INS_VSHUF_D,
	LoongArch_INS_VSHUF_H,
	LoongArch_INS_VSHUF_W,
	LoongArch_INS_VSIGNCOV_B,
	LoongArch_INS_VSIGNCOV_D,
	LoongArch_INS_VSIGNCOV_H,
	LoongArch_INS_VSIGNCOV_W,
	LoongArch_INS_VSLEI_B,
	LoongArch_INS_VSLEI_BU,
	LoongArch_INS_VSLEI_D,
	LoongArch_INS_VSLEI_DU,
	LoongArch_INS_VSLEI_H,
	LoongArch_INS_VSLEI_HU,
	LoongArch_INS_VSLEI_W,
	LoongArch_INS_VSLEI_WU,
	LoongArch_INS_VSLE_B,
	LoongArch_INS_VSLE_BU,
	LoongArch_INS_VSLE_D,
	LoongArch_INS_VSLE_DU,
	LoongArch_INS_VSLE_H,
	LoongArch_INS_VSLE_HU,
	LoongArch_INS_VSLE_W,
	LoongArch_INS_VSLE_WU,
	LoongArch_INS_VSLLI_B,
	LoongArch_INS_VSLLI_D,
	LoongArch_INS_VSLLI_H,
	LoongArch_INS_VSLLI_W,
	LoongArch_INS_VSLLWIL_DU_WU,
	LoongArch_INS_VSLLWIL_D_W,
	LoongArch_INS_VSLLWIL_HU_BU,
	LoongArch_INS_VSLLWIL_H_B,
	LoongArch_INS_VSLLWIL_WU_HU,
	LoongArch_INS_VSLLWIL_W_H,
	LoongArch_INS_VSLL_B,
	LoongArch_INS_VSLL_D,
	LoongArch_INS_VSLL_H,
	LoongArch_INS_VSLL_W,
	LoongArch_INS_VSLTI_B,
	LoongArch_INS_VSLTI_BU,
	LoongArch_INS_VSLTI_D,
	LoongArch_INS_VSLTI_DU,
	LoongArch_INS_VSLTI_H,
	LoongArch_INS_VSLTI_HU,
	LoongArch_INS_VSLTI_W,
	LoongArch_INS_VSLTI_WU,
	LoongArch_INS_VSLT_B,
	LoongArch_INS_VSLT_BU,
	LoongArch_INS_VSLT_D,
	LoongArch_INS_VSLT_DU,
	LoongArch_INS_VSLT_H,
	LoongArch_INS_VSLT_HU,
	LoongArch_INS_VSLT_W,
	LoongArch_INS_VSLT_WU,
	LoongArch_INS_VSRAI_B,
	LoongArch_INS_VSRAI_D,
	LoongArch_INS_VSRAI_H,
	LoongArch_INS_VSRAI_W,
	LoongArch_INS_VSRANI_B_H,
	LoongArch_INS_VSRANI_D_Q,
	LoongArch_INS_VSRANI_H_W,
	LoongArch_INS_VSRANI_W_D,
	LoongArch_INS_VSRAN_B_H,
	LoongArch_INS_VSRAN_H_W,
	LoongArch_INS_VSRAN_W_D,
	LoongArch_INS_VSRARI_B,
	LoongArch_INS_VSRARI_D,
	LoongArch_INS_VSRARI_H,
	LoongArch_INS_VSRARI_W,
	LoongArch_INS_VSRARNI_B_H,
	LoongArch_INS_VSRARNI_D_Q,
	LoongArch_INS_VSRARNI_H_W,
	LoongArch_INS_VSRARNI_W_D,
	LoongArch_INS_VSRARN_B_H,
	LoongArch_INS_VSRARN_H_W,
	LoongArch_INS_VSRARN_W_D,
	LoongArch_INS_VSRAR_B,
	LoongArch_INS_VSRAR_D,
	LoongArch_INS_VSRAR_H,
	LoongArch_INS_VSRAR_W,
	LoongArch_INS_VSRA_B,
	LoongArch_INS_VSRA_D,
	LoongArch_INS_VSRA_H,
	LoongArch_INS_VSRA_W,
	LoongArch_INS_VSRLI_B,
	LoongArch_INS_VSRLI_D,
	LoongArch_INS_VSRLI_H,
	LoongArch_INS_VSRLI_W,
	LoongArch_INS_VSRLNI_B_H,
	LoongArch_INS_VSRLNI_D_Q,
	LoongArch_INS_VSRLNI_H_W,
	LoongArch_INS_VSRLNI_W_D,
	LoongArch_INS_VSRLN_B_H,
	LoongArch_INS_VSRLN_H_W,
	LoongArch_INS_VSRLN_W_D,
	LoongArch_INS_VSRLRI_B,
	LoongArch_INS_VSRLRI_D,
	LoongArch_INS_VSRLRI_H,
	LoongArch_INS_VSRLRI_W,
	LoongArch_INS_VSRLRNI_B_H,
	LoongArch_INS_VSRLRNI_D_Q,
	LoongArch_INS_VSRLRNI_H_W,
	LoongArch_INS_VSRLRNI_W_D,
	LoongArch_INS_VSRLRN_B_H,
	LoongArch_INS_VSRLRN_H_W,
	LoongArch_INS_VSRLRN_W_D,
	LoongArch_INS_VSRLR_B,
	LoongArch_INS_VSRLR_D,
	LoongArch_INS_VSRLR_H,
	LoongArch_INS_VSRLR_W,
	LoongArch_INS_VSRL_B,
	LoongArch_INS_VSRL_D,
	LoongArch_INS_VSRL_H,
	LoongArch_INS_VSRL_W,
	LoongArch_INS_VSSRANI_BU_H,
	LoongArch_INS_VSSRANI_B_H,
	LoongArch_INS_VSSRANI_DU_Q,
	LoongArch_INS_VSSRANI_D_Q,
	LoongArch_INS_VSSRANI_HU_W,
	LoongArch_INS_VSSRANI_H_W,
	LoongArch_INS_VSSRANI_WU_D,
	LoongArch_INS_VSSRANI_W_D,
	LoongArch_INS_VSSRAN_BU_H,
	LoongArch_INS_VSSRAN_B_H,
	LoongArch_INS_VSSRAN_HU_W,
	LoongArch_INS_VSSRAN_H_W,
	LoongArch_INS_VSSRAN_WU_D,
	LoongArch_INS_VSSRAN_W_D,
	LoongArch_INS_VSSRARNI_BU_H,
	LoongArch_INS_VSSRARNI_B_H,
	LoongArch_INS_VSSRARNI_DU_Q,
	LoongArch_INS_VSSRARNI_D_Q,
	LoongArch_INS_VSSRARNI_HU_W,
	LoongArch_INS_VSSRARNI_H_W,
	LoongArch_INS_VSSRARNI_WU_D,
	LoongArch_INS_VSSRARNI_W_D,
	LoongArch_INS_VSSRARN_BU_H,
	LoongArch_INS_VSSRARN_B_H,
	LoongArch_INS_VSSRARN_HU_W,
	LoongArch_INS_VSSRARN_H_W,
	LoongArch_INS_VSSRARN_WU_D,
	LoongArch_INS_VSSRARN_W_D,
	LoongArch_INS_VSSRLNI_BU_H,
	LoongArch_INS_VSSRLNI_B_H,
	LoongArch_INS_VSSRLNI_DU_Q,
	LoongArch_INS_VSSRLNI_D_Q,
	LoongArch_INS_VSSRLNI_HU_W,
	LoongArch_INS_VSSRLNI_H_W,
	LoongArch_INS_VSSRLNI_WU_D,
	LoongArch_INS_VSSRLNI_W_D,
	LoongArch_INS_VSSRLN_BU_H,
	LoongArch_INS_VSSRLN_B_H,
	LoongArch_INS_VSSRLN_HU_W,
	LoongArch_INS_VSSRLN_H_W,
	LoongArch_INS_VSSRLN_WU_D,
	LoongArch_INS_VSSRLN_W_D,
	LoongArch_INS_VSSRLRNI_BU_H,
	LoongArch_INS_VSSRLRNI_B_H,
	LoongArch_INS_VSSRLRNI_DU_Q,
	LoongArch_INS_VSSRLRNI_D_Q,
	LoongArch_INS_VSSRLRNI_HU_W,
	LoongArch_INS_VSSRLRNI_H_W,
	LoongArch_INS_VSSRLRNI_WU_D,
	LoongArch_INS_VSSRLRNI_W_D,
	LoongArch_INS_VSSRLRN_BU_H,
	LoongArch_INS_VSSRLRN_B_H,
	LoongArch_INS_VSSRLRN_HU_W,
	LoongArch_INS_VSSRLRN_H_W,
	LoongArch_INS_VSSRLRN_WU_D,
	LoongArch_INS_VSSRLRN_W_D,
	LoongArch_INS_VSSUB_B,
	LoongArch_INS_VSSUB_BU,
	LoongArch_INS_VSSUB_D,
	LoongArch_INS_VSSUB_DU,
	LoongArch_INS_VSSUB_H,
	LoongArch_INS_VSSUB_HU,
	LoongArch_INS_VSSUB_W,
	LoongArch_INS_VSSUB_WU,
	LoongArch_INS_VST,
	LoongArch_INS_VSTELM_B,
	LoongArch_INS_VSTELM_D,
	LoongArch_INS_VSTELM_H,
	LoongArch_INS_VSTELM_W,
	LoongArch_INS_VSTX,
	LoongArch_INS_VSUBI_BU,
	LoongArch_INS_VSUBI_DU,
	LoongArch_INS_VSUBI_HU,
	LoongArch_INS_VSUBI_WU,
	LoongArch_INS_VSUBWEV_D_W,
	LoongArch_INS_VSUBWEV_D_WU,
	LoongArch_INS_VSUBWEV_H_B,
	LoongArch_INS_VSUBWEV_H_BU,
	LoongArch_INS_VSUBWEV_Q_D,
	LoongArch_INS_VSUBWEV_Q_DU,
	LoongArch_INS_VSUBWEV_W_H,
	LoongArch_INS_VSUBWEV_W_HU,
	LoongArch_INS_VSUBWOD_D_W,
	LoongArch_INS_VSUBWOD_D_WU,
	LoongArch_INS_VSUBWOD_H_B,
	LoongArch_INS_VSUBWOD_H_BU,
	LoongArch_INS_VSUBWOD_Q_D,
	LoongArch_INS_VSUBWOD_Q_DU,
	LoongArch_INS_VSUBWOD_W_H,
	LoongArch_INS_VSUBWOD_W_HU,
	LoongArch_INS_VSUB_B,
	LoongArch_INS_VSUB_D,
	LoongArch_INS_VSUB_H,
	LoongArch_INS_VSUB_Q,
	LoongArch_INS_VSUB_W,
	LoongArch_INS_VXORI_B,
	LoongArch_INS_VXOR_V,
	LoongArch_INS_X86ADC_B,
	LoongArch_INS_X86ADC_D,
	LoongArch_INS_X86ADC_H,
	LoongArch_INS_X86ADC_W,
	LoongArch_INS_X86ADD_B,
	LoongArch_INS_X86ADD_D,
	LoongArch_INS_X86ADD_DU,
	LoongArch_INS_X86ADD_H,
	LoongArch_INS_X86ADD_W,
	LoongArch_INS_X86ADD_WU,
	LoongArch_INS_X86AND_B,
	LoongArch_INS_X86AND_D,
	LoongArch_INS_X86AND_H,
	LoongArch_INS_X86AND_W,
	LoongArch_INS_X86CLRTM,
	LoongArch_INS_X86DECTOP,
	LoongArch_INS_X86DEC_B,
	LoongArch_INS_X86DEC_D,
	LoongArch_INS_X86DEC_H,
	LoongArch_INS_X86DEC_W,
	LoongArch_INS_X86INCTOP,
	LoongArch_INS_X86INC_B,
	LoongArch_INS_X86INC_D,
	LoongArch_INS_X86INC_H,
	LoongArch_INS_X86INC_W,
	LoongArch_INS_X86MFFLAG,
	LoongArch_INS_X86MFTOP,
	LoongArch_INS_X86MTFLAG,
	LoongArch_INS_X86MTTOP,
	LoongArch_INS_X86MUL_B,
	LoongArch_INS_X86MUL_BU,
	LoongArch_INS_X86MUL_D,
	LoongArch_INS_X86MUL_DU,
	LoongArch_INS_X86MUL_H,
	LoongArch_INS_X86MUL_HU,
	LoongArch_INS_X86MUL_W,
	LoongArch_INS_X86MUL_WU,
	LoongArch_INS_X86OR_B,
	LoongArch_INS_X86OR_D,
	LoongArch_INS_X86OR_H,
	LoongArch_INS_X86OR_W,
	LoongArch_INS_X86RCLI_B,
	LoongArch_INS_X86RCLI_D,
	LoongArch_INS_X86RCLI_H,
	LoongArch_INS_X86RCLI_W,
	LoongArch_INS_X86RCL_B,
	LoongArch_INS_X86RCL_D,
	LoongArch_INS_X86RCL_H,
	LoongArch_INS_X86RCL_W,
	LoongArch_INS_X86RCRI_B,
	LoongArch_INS_X86RCRI_D,
	LoongArch_INS_X86RCRI_H,
	LoongArch_INS_X86RCRI_W,
	LoongArch_INS_X86RCR_B,
	LoongArch_INS_X86RCR_D,
	LoongArch_INS_X86RCR_H,
	LoongArch_INS_X86RCR_W,
	LoongArch_INS_X86ROTLI_B,
	LoongArch_INS_X86ROTLI_D,
	LoongArch_INS_X86ROTLI_H,
	LoongArch_INS_X86ROTLI_W,
	LoongArch_INS_X86ROTL_B,
	LoongArch_INS_X86ROTL_D,
	LoongArch_INS_X86ROTL_H,
	LoongArch_INS_X86ROTL_W,
	LoongArch_INS_X86ROTRI_B,
	LoongArch_INS_X86ROTRI_D,
	LoongArch_INS_X86ROTRI_H,
	LoongArch_INS_X86ROTRI_W,
	LoongArch_INS_X86ROTR_B,
	LoongArch_INS_X86ROTR_D,
	LoongArch_INS_X86ROTR_H,
	LoongArch_INS_X86ROTR_W,
	LoongArch_INS_X86SBC_B,
	LoongArch_INS_X86SBC_D,
	LoongArch_INS_X86SBC_H,
	LoongArch_INS_X86SBC_W,
	LoongArch_INS_X86SETTAG,
	LoongArch_INS_X86SETTM,
	LoongArch_INS_X86SLLI_B,
	LoongArch_INS_X86SLLI_D,
	LoongArch_INS_X86SLLI_H,
	LoongArch_INS_X86SLLI_W,
	LoongArch_INS_X86SLL_B,
	LoongArch_INS_X86SLL_D,
	LoongArch_INS_X86SLL_H,
	LoongArch_INS_X86SLL_W,
	LoongArch_INS_X86SRAI_B,
	LoongArch_INS_X86SRAI_D,
	LoongArch_INS_X86SRAI_H,
	LoongArch_INS_X86SRAI_W,
	LoongArch_INS_X86SRA_B,
	LoongArch_INS_X86SRA_D,
	LoongArch_INS_X86SRA_H,
	LoongArch_INS_X86SRA_W,
	LoongArch_INS_X86SRLI_B,
	LoongArch_INS_X86SRLI_D,
	LoongArch_INS_X86SRLI_H,
	LoongArch_INS_X86SRLI_W,
	LoongArch_INS_X86SRL_B,
	LoongArch_INS_X86SRL_D,
	LoongArch_INS_X86SRL_H,
	LoongArch_INS_X86SRL_W,
	LoongArch_INS_X86SUB_B,
	LoongArch_INS_X86SUB_D,
	LoongArch_INS_X86SUB_DU,
	LoongArch_INS_X86SUB_H,
	LoongArch_INS_X86SUB_W,
	LoongArch_INS_X86SUB_WU,
	LoongArch_INS_X86XOR_B,
	LoongArch_INS_X86XOR_D,
	LoongArch_INS_X86XOR_H,
	LoongArch_INS_X86XOR_W,
	LoongArch_INS_XOR,
	LoongArch_INS_XORI,
	LoongArch_INS_XVABSD_B,
	LoongArch_INS_XVABSD_BU,
	LoongArch_INS_XVABSD_D,
	LoongArch_INS_XVABSD_DU,
	LoongArch_INS_XVABSD_H,
	LoongArch_INS_XVABSD_HU,
	LoongArch_INS_XVABSD_W,
	LoongArch_INS_XVABSD_WU,
	LoongArch_INS_XVADDA_B,
	LoongArch_INS_XVADDA_D,
	LoongArch_INS_XVADDA_H,
	LoongArch_INS_XVADDA_W,
	LoongArch_INS_XVADDI_BU,
	LoongArch_INS_XVADDI_DU,
	LoongArch_INS_XVADDI_HU,
	LoongArch_INS_XVADDI_WU,
	LoongArch_INS_XVADDWEV_D_W,
	LoongArch_INS_XVADDWEV_D_WU,
	LoongArch_INS_XVADDWEV_D_WU_W,
	LoongArch_INS_XVADDWEV_H_B,
	LoongArch_INS_XVADDWEV_H_BU,
	LoongArch_INS_XVADDWEV_H_BU_B,
	LoongArch_INS_XVADDWEV_Q_D,
	LoongArch_INS_XVADDWEV_Q_DU,
	LoongArch_INS_XVADDWEV_Q_DU_D,
	LoongArch_INS_XVADDWEV_W_H,
	LoongArch_INS_XVADDWEV_W_HU,
	LoongArch_INS_XVADDWEV_W_HU_H,
	LoongArch_INS_XVADDWOD_D_W,
	LoongArch_INS_XVADDWOD_D_WU,
	LoongArch_INS_XVADDWOD_D_WU_W,
	LoongArch_INS_XVADDWOD_H_B,
	LoongArch_INS_XVADDWOD_H_BU,
	LoongArch_INS_XVADDWOD_H_BU_B,
	LoongArch_INS_XVADDWOD_Q_D,
	LoongArch_INS_XVADDWOD_Q_DU,
	LoongArch_INS_XVADDWOD_Q_DU_D,
	LoongArch_INS_XVADDWOD_W_H,
	LoongArch_INS_XVADDWOD_W_HU,
	LoongArch_INS_XVADDWOD_W_HU_H,
	LoongArch_INS_XVADD_B,
	LoongArch_INS_XVADD_D,
	LoongArch_INS_XVADD_H,
	LoongArch_INS_XVADD_Q,
	LoongArch_INS_XVADD_W,
	LoongArch_INS_XVANDI_B,
	LoongArch_INS_XVANDN_V,
	LoongArch_INS_XVAND_V,
	LoongArch_INS_XVAVGR_B,
	LoongArch_INS_XVAVGR_BU,
	LoongArch_INS_XVAVGR_D,
	LoongArch_INS_XVAVGR_DU,
	LoongArch_INS_XVAVGR_H,
	LoongArch_INS_XVAVGR_HU,
	LoongArch_INS_XVAVGR_W,
	LoongArch_INS_XVAVGR_WU,
	LoongArch_INS_XVAVG_B,
	LoongArch_INS_XVAVG_BU,
	LoongArch_INS_XVAVG_D,
	LoongArch_INS_XVAVG_DU,
	LoongArch_INS_XVAVG_H,
	LoongArch_INS_XVAVG_HU,
	LoongArch_INS_XVAVG_W,
	LoongArch_INS_XVAVG_WU,
	LoongArch_INS_XVBITCLRI_B,
	LoongArch_INS_XVBITCLRI_D,
	LoongArch_INS_XVBITCLRI_H,
	LoongArch_INS_XVBITCLRI_W,
	LoongArch_INS_XVBITCLR_B,
	LoongArch_INS_XVBITCLR_D,
	LoongArch_INS_XVBITCLR_H,
	LoongArch_INS_XVBITCLR_W,
	LoongArch_INS_XVBITREVI_B,
	LoongArch_INS_XVBITREVI_D,
	LoongArch_INS_XVBITREVI_H,
	LoongArch_INS_XVBITREVI_W,
	LoongArch_INS_XVBITREV_B,
	LoongArch_INS_XVBITREV_D,
	LoongArch_INS_XVBITREV_H,
	LoongArch_INS_XVBITREV_W,
	LoongArch_INS_XVBITSELI_B,
	LoongArch_INS_XVBITSEL_V,
	LoongArch_INS_XVBITSETI_B,
	LoongArch_INS_XVBITSETI_D,
	LoongArch_INS_XVBITSETI_H,
	LoongArch_INS_XVBITSETI_W,
	LoongArch_INS_XVBITSET_B,
	LoongArch_INS_XVBITSET_D,
	LoongArch_INS_XVBITSET_H,
	LoongArch_INS_XVBITSET_W,
	LoongArch_INS_XVBSLL_V,
	LoongArch_INS_XVBSRL_V,
	LoongArch_INS_XVCLO_B,
	LoongArch_INS_XVCLO_D,
	LoongArch_INS_XVCLO_H,
	LoongArch_INS_XVCLO_W,
	LoongArch_INS_XVCLZ_B,
	LoongArch_INS_XVCLZ_D,
	LoongArch_INS_XVCLZ_H,
	LoongArch_INS_XVCLZ_W,
	LoongArch_INS_XVDIV_B,
	LoongArch_INS_XVDIV_BU,
	LoongArch_INS_XVDIV_D,
	LoongArch_INS_XVDIV_DU,
	LoongArch_INS_XVDIV_H,
	LoongArch_INS_XVDIV_HU,
	LoongArch_INS_XVDIV_W,
	LoongArch_INS_XVDIV_WU,
	LoongArch_INS_XVEXTH_DU_WU,
	LoongArch_INS_XVEXTH_D_W,
	LoongArch_INS_XVEXTH_HU_BU,
	LoongArch_INS_XVEXTH_H_B,
	LoongArch_INS_XVEXTH_QU_DU,
	LoongArch_INS_XVEXTH_Q_D,
	LoongArch_INS_XVEXTH_WU_HU,
	LoongArch_INS_XVEXTH_W_H,
	LoongArch_INS_XVEXTL_QU_DU,
	LoongArch_INS_XVEXTL_Q_D,
	LoongArch_INS_XVEXTRINS_B,
	LoongArch_INS_XVEXTRINS_D,
	LoongArch_INS_XVEXTRINS_H,
	LoongArch_INS_XVEXTRINS_W,
	LoongArch_INS_XVFADD_D,
	LoongArch_INS_XVFADD_S,
	LoongArch_INS_XVFCLASS_D,
	LoongArch_INS_XVFCLASS_S,
	LoongArch_INS_XVFCMP_CAF_D,
	LoongArch_INS_XVFCMP_CAF_S,
	LoongArch_INS_XVFCMP_CEQ_D,
	LoongArch_INS_XVFCMP_CEQ_S,
	LoongArch_INS_XVFCMP_CLE_D,
	LoongArch_INS_XVFCMP_CLE_S,
	LoongArch_INS_XVFCMP_CLT_D,
	LoongArch_INS_XVFCMP_CLT_S,
	LoongArch_INS_XVFCMP_CNE_D,
	LoongArch_INS_XVFCMP_CNE_S,
	LoongArch_INS_XVFCMP_COR_D,
	LoongArch_INS_XVFCMP_COR_S,
	LoongArch_INS_XVFCMP_CUEQ_D,
	LoongArch_INS_XVFCMP_CUEQ_S,
	LoongArch_INS_XVFCMP_CULE_D,
	LoongArch_INS_XVFCMP_CULE_S,
	LoongArch_INS_XVFCMP_CULT_D,
	LoongArch_INS_XVFCMP_CULT_S,
	LoongArch_INS_XVFCMP_CUNE_D,
	LoongArch_INS_XVFCMP_CUNE_S,
	LoongArch_INS_XVFCMP_CUN_D,
	LoongArch_INS_XVFCMP_CUN_S,
	LoongArch_INS_XVFCMP_SAF_D,
	LoongArch_INS_XVFCMP_SAF_S,
	LoongArch_INS_XVFCMP_SEQ_D,
	LoongArch_INS_XVFCMP_SEQ_S,
	LoongArch_INS_XVFCMP_SLE_D,
	LoongArch_INS_XVFCMP_SLE_S,
	LoongArch_INS_XVFCMP_SLT_D,
	LoongArch_INS_XVFCMP_SLT_S,
	LoongArch_INS_XVFCMP_SNE_D,
	LoongArch_INS_XVFCMP_SNE_S,
	LoongArch_INS_XVFCMP_SOR_D,
	LoongArch_INS_XVFCMP_SOR_S,
	LoongArch_INS_XVFCMP_SUEQ_D,
	LoongArch_INS_XVFCMP_SUEQ_S,
	LoongArch_INS_XVFCMP_SULE_D,
	LoongArch_INS_XVFCMP_SULE_S,
	LoongArch_INS_XVFCMP_SULT_D,
	LoongArch_INS_XVFCMP_SULT_S,
	LoongArch_INS_XVFCMP_SUNE_D,
	LoongArch_INS_XVFCMP_SUNE_S,
	LoongArch_INS_XVFCMP_SUN_D,
	LoongArch_INS_XVFCMP_SUN_S,
	LoongArch_INS_XVFCVTH_D_S,
	LoongArch_INS_XVFCVTH_S_H,
	LoongArch_INS_XVFCVTL_D_S,
	LoongArch_INS_XVFCVTL_S_H,
	LoongArch_INS_XVFCVT_H_S,
	LoongArch_INS_XVFCVT_S_D,
	LoongArch_INS_XVFDIV_D,
	LoongArch_INS_XVFDIV_S,
	LoongArch_INS_XVFFINTH_D_W,
	LoongArch_INS_XVFFINTL_D_W,
	LoongArch_INS_XVFFINT_D_L,
	LoongArch_INS_XVFFINT_D_LU,
	LoongArch_INS_XVFFINT_S_L,
	LoongArch_INS_XVFFINT_S_W,
	LoongArch_INS_XVFFINT_S_WU,
	LoongArch_INS_XVFLOGB_D,
	LoongArch_INS_XVFLOGB_S,
	LoongArch_INS_XVFMADD_D,
	LoongArch_INS_XVFMADD_S,
	LoongArch_INS_XVFMAXA_D,
	LoongArch_INS_XVFMAXA_S,
	LoongArch_INS_XVFMAX_D,
	LoongArch_INS_XVFMAX_S,
	LoongArch_INS_XVFMINA_D,
	LoongArch_INS_XVFMINA_S,
	LoongArch_INS_XVFMIN_D,
	LoongArch_INS_XVFMIN_S,
	LoongArch_INS_XVFMSUB_D,
	LoongArch_INS_XVFMSUB_S,
	LoongArch_INS_XVFMUL_D,
	LoongArch_INS_XVFMUL_S,
	LoongArch_INS_XVFNMADD_D,
	LoongArch_INS_XVFNMADD_S,
	LoongArch_INS_XVFNMSUB_D,
	LoongArch_INS_XVFNMSUB_S,
	LoongArch_INS_XVFRECIPE_D,
	LoongArch_INS_XVFRECIPE_S,
	LoongArch_INS_XVFRECIP_D,
	LoongArch_INS_XVFRECIP_S,
	LoongArch_INS_XVFRINTRM_D,
	LoongArch_INS_XVFRINTRM_S,
	LoongArch_INS_XVFRINTRNE_D,
	LoongArch_INS_XVFRINTRNE_S,
	LoongArch_INS_XVFRINTRP_D,
	LoongArch_INS_XVFRINTRP_S,
	LoongArch_INS_XVFRINTRZ_D,
	LoongArch_INS_XVFRINTRZ_S,
	LoongArch_INS_XVFRINT_D,
	LoongArch_INS_XVFRINT_S,
	LoongArch_INS_XVFRSQRTE_D,
	LoongArch_INS_XVFRSQRTE_S,
	LoongArch_INS_XVFRSQRT_D,
	LoongArch_INS_XVFRSQRT_S,
	LoongArch_INS_XVFRSTPI_B,
	LoongArch_INS_XVFRSTPI_H,
	LoongArch_INS_XVFRSTP_B,
	LoongArch_INS_XVFRSTP_H,
	LoongArch_INS_XVFSQRT_D,
	LoongArch_INS_XVFSQRT_S,
	LoongArch_INS_XVFSUB_D,
	LoongArch_INS_XVFSUB_S,
	LoongArch_INS_XVFTINTH_L_S,
	LoongArch_INS_XVFTINTL_L_S,
	LoongArch_INS_XVFTINTRMH_L_S,
	LoongArch_INS_XVFTINTRML_L_S,
	LoongArch_INS_XVFTINTRM_L_D,
	LoongArch_INS_XVFTINTRM_W_D,
	LoongArch_INS_XVFTINTRM_W_S,
	LoongArch_INS_XVFTINTRNEH_L_S,
	LoongArch_INS_XVFTINTRNEL_L_S,
	LoongArch_INS_XVFTINTRNE_L_D,
	LoongArch_INS_XVFTINTRNE_W_D,
	LoongArch_INS_XVFTINTRNE_W_S,
	LoongArch_INS_XVFTINTRPH_L_S,
	LoongArch_INS_XVFTINTRPL_L_S,
	LoongArch_INS_XVFTINTRP_L_D,
	LoongArch_INS_XVFTINTRP_W_D,
	LoongArch_INS_XVFTINTRP_W_S,
	LoongArch_INS_XVFTINTRZH_L_S,
	LoongArch_INS_XVFTINTRZL_L_S,
	LoongArch_INS_XVFTINTRZ_LU_D,
	LoongArch_INS_XVFTINTRZ_L_D,
	LoongArch_INS_XVFTINTRZ_WU_S,
	LoongArch_INS_XVFTINTRZ_W_D,
	LoongArch_INS_XVFTINTRZ_W_S,
	LoongArch_INS_XVFTINT_LU_D,
	LoongArch_INS_XVFTINT_L_D,
	LoongArch_INS_XVFTINT_WU_S,
	LoongArch_INS_XVFTINT_W_D,
	LoongArch_INS_XVFTINT_W_S,
	LoongArch_INS_XVHADDW_DU_WU,
	LoongArch_INS_XVHADDW_D_W,
	LoongArch_INS_XVHADDW_HU_BU,
	LoongArch_INS_XVHADDW_H_B,
	LoongArch_INS_XVHADDW_QU_DU,
	LoongArch_INS_XVHADDW_Q_D,
	LoongArch_INS_XVHADDW_WU_HU,
	LoongArch_INS_XVHADDW_W_H,
	LoongArch_INS_XVHSELI_D,
	LoongArch_INS_XVHSUBW_DU_WU,
	LoongArch_INS_XVHSUBW_D_W,
	LoongArch_INS_XVHSUBW_HU_BU,
	LoongArch_INS_XVHSUBW_H_B,
	LoongArch_INS_XVHSUBW_QU_DU,
	LoongArch_INS_XVHSUBW_Q_D,
	LoongArch_INS_XVHSUBW_WU_HU,
	LoongArch_INS_XVHSUBW_W_H,
	LoongArch_INS_XVILVH_B,
	LoongArch_INS_XVILVH_D,
	LoongArch_INS_XVILVH_H,
	LoongArch_INS_XVILVH_W,
	LoongArch_INS_XVILVL_B,
	LoongArch_INS_XVILVL_D,
	LoongArch_INS_XVILVL_H,
	LoongArch_INS_XVILVL_W,
	LoongArch_INS_XVINSGR2VR_D,
	LoongArch_INS_XVINSGR2VR_W,
	LoongArch_INS_XVINSVE0_D,
	LoongArch_INS_XVINSVE0_W,
	LoongArch_INS_XVLD,
	LoongArch_INS_XVLDI,
	LoongArch_INS_XVLDREPL_B,
	LoongArch_INS_XVLDREPL_D,
	LoongArch_INS_XVLDREPL_H,
	LoongArch_INS_XVLDREPL_W,
	LoongArch_INS_XVLDX,
	LoongArch_INS_XVMADDWEV_D_W,
	LoongArch_INS_XVMADDWEV_D_WU,
	LoongArch_INS_XVMADDWEV_D_WU_W,
	LoongArch_INS_XVMADDWEV_H_B,
	LoongArch_INS_XVMADDWEV_H_BU,
	LoongArch_INS_XVMADDWEV_H_BU_B,
	LoongArch_INS_XVMADDWEV_Q_D,
	LoongArch_INS_XVMADDWEV_Q_DU,
	LoongArch_INS_XVMADDWEV_Q_DU_D,
	LoongArch_INS_XVMADDWEV_W_H,
	LoongArch_INS_XVMADDWEV_W_HU,
	LoongArch_INS_XVMADDWEV_W_HU_H,
	LoongArch_INS_XVMADDWOD_D_W,
	LoongArch_INS_XVMADDWOD_D_WU,
	LoongArch_INS_XVMADDWOD_D_WU_W,
	LoongArch_INS_XVMADDWOD_H_B,
	LoongArch_INS_XVMADDWOD_H_BU,
	LoongArch_INS_XVMADDWOD_H_BU_B,
	LoongArch_INS_XVMADDWOD_Q_D,
	LoongArch_INS_XVMADDWOD_Q_DU,
	LoongArch_INS_XVMADDWOD_Q_DU_D,
	LoongArch_INS_XVMADDWOD_W_H,
	LoongArch_INS_XVMADDWOD_W_HU,
	LoongArch_INS_XVMADDWOD_W_HU_H,
	LoongArch_INS_XVMADD_B,
	LoongArch_INS_XVMADD_D,
	LoongArch_INS_XVMADD_H,
	LoongArch_INS_XVMADD_W,
	LoongArch_INS_XVMAXI_B,
	LoongArch_INS_XVMAXI_BU,
	LoongArch_INS_XVMAXI_D,
	LoongArch_INS_XVMAXI_DU,
	LoongArch_INS_XVMAXI_H,
	LoongArch_INS_XVMAXI_HU,
	LoongArch_INS_XVMAXI_W,
	LoongArch_INS_XVMAXI_WU,
	LoongArch_INS_XVMAX_B,
	LoongArch_INS_XVMAX_BU,
	LoongArch_INS_XVMAX_D,
	LoongArch_INS_XVMAX_DU,
	LoongArch_INS_XVMAX_H,
	LoongArch_INS_XVMAX_HU,
	LoongArch_INS_XVMAX_W,
	LoongArch_INS_XVMAX_WU,
	LoongArch_INS_XVMINI_B,
	LoongArch_INS_XVMINI_BU,
	LoongArch_INS_XVMINI_D,
	LoongArch_INS_XVMINI_DU,
	LoongArch_INS_XVMINI_H,
	LoongArch_INS_XVMINI_HU,
	LoongArch_INS_XVMINI_W,
	LoongArch_INS_XVMINI_WU,
	LoongArch_INS_XVMIN_B,
	LoongArch_INS_XVMIN_BU,
	LoongArch_INS_XVMIN_D,
	LoongArch_INS_XVMIN_DU,
	LoongArch_INS_XVMIN_H,
	LoongArch_INS_XVMIN_HU,
	LoongArch_INS_XVMIN_W,
	LoongArch_INS_XVMIN_WU,
	LoongArch_INS_XVMOD_B,
	LoongArch_INS_XVMOD_BU,
	LoongArch_INS_XVMOD_D,
	LoongArch_INS_XVMOD_DU,
	LoongArch_INS_XVMOD_H,
	LoongArch_INS_XVMOD_HU,
	LoongArch_INS_XVMOD_W,
	LoongArch_INS_XVMOD_WU,
	LoongArch_INS_XVMSKGEZ_B,
	LoongArch_INS_XVMSKLTZ_B,
	LoongArch_INS_XVMSKLTZ_D,
	LoongArch_INS_XVMSKLTZ_H,
	LoongArch_INS_XVMSKLTZ_W,
	LoongArch_INS_XVMSKNZ_B,
	LoongArch_INS_XVMSUB_B,
	LoongArch_INS_XVMSUB_D,
	LoongArch_INS_XVMSUB_H,
	LoongArch_INS_XVMSUB_W,
	LoongArch_INS_XVMUH_B,
	LoongArch_INS_XVMUH_BU,
	LoongArch_INS_XVMUH_D,
	LoongArch_INS_XVMUH_DU,
	LoongArch_INS_XVMUH_H,
	LoongArch_INS_XVMUH_HU,
	LoongArch_INS_XVMUH_W,
	LoongArch_INS_XVMUH_WU,
	LoongArch_INS_XVMULWEV_D_W,
	LoongArch_INS_XVMULWEV_D_WU,
	LoongArch_INS_XVMULWEV_D_WU_W,
	LoongArch_INS_XVMULWEV_H_B,
	LoongArch_INS_XVMULWEV_H_BU,
	LoongArch_INS_XVMULWEV_H_BU_B,
	LoongArch_INS_XVMULWEV_Q_D,
	LoongArch_INS_XVMULWEV_Q_DU,
	LoongArch_INS_XVMULWEV_Q_DU_D,
	LoongArch_INS_XVMULWEV_W_H,
	LoongArch_INS_XVMULWEV_W_HU,
	LoongArch_INS_XVMULWEV_W_HU_H,
	LoongArch_INS_XVMULWOD_D_W,
	LoongArch_INS_XVMULWOD_D_WU,
	LoongArch_INS_XVMULWOD_D_WU_W,
	LoongArch_INS_XVMULWOD_H_B,
	LoongArch_INS_XVMULWOD_H_BU,
	LoongArch_INS_XVMULWOD_H_BU_B,
	LoongArch_INS_XVMULWOD_Q_D,
	LoongArch_INS_XVMULWOD_Q_DU,
	LoongArch_INS_XVMULWOD_Q_DU_D,
	LoongArch_INS_XVMULWOD_W_H,
	LoongArch_INS_XVMULWOD_W_HU,
	LoongArch_INS_XVMULWOD_W_HU_H,
	LoongArch_INS_XVMUL_B,
	LoongArch_INS_XVMUL_D,
	LoongArch_INS_XVMUL_H,
	LoongArch_INS_XVMUL_W,
	LoongArch_INS_XVNEG_B,
	LoongArch_INS_XVNEG_D,
	LoongArch_INS_XVNEG_H,
	LoongArch_INS_XVNEG_W,
	LoongArch_INS_XVNORI_B,
	LoongArch_INS_XVNOR_V,
	LoongArch_INS_XVORI_B,
	LoongArch_INS_XVORN_V,
	LoongArch_INS_XVOR_V,
	LoongArch_INS_XVPACKEV_B,
	LoongArch_INS_XVPACKEV_D,
	LoongArch_INS_XVPACKEV_H,
	LoongArch_INS_XVPACKEV_W,
	LoongArch_INS_XVPACKOD_B,
	LoongArch_INS_XVPACKOD_D,
	LoongArch_INS_XVPACKOD_H,
	LoongArch_INS_XVPACKOD_W,
	LoongArch_INS_XVPCNT_B,
	LoongArch_INS_XVPCNT_D,
	LoongArch_INS_XVPCNT_H,
	LoongArch_INS_XVPCNT_W,
	LoongArch_INS_XVPERMI_D,
	LoongArch_INS_XVPERMI_Q,
	LoongArch_INS_XVPERMI_W,
	LoongArch_INS_XVPERM_W,
	LoongArch_INS_XVPICKEV_B,
	LoongArch_INS_XVPICKEV_D,
	LoongArch_INS_XVPICKEV_H,
	LoongArch_INS_XVPICKEV_W,
	LoongArch_INS_XVPICKOD_B,
	LoongArch_INS_XVPICKOD_D,
	LoongArch_INS_XVPICKOD_H,
	LoongArch_INS_XVPICKOD_W,
	LoongArch_INS_XVPICKVE2GR_D,
	LoongArch_INS_XVPICKVE2GR_DU,
	LoongArch_INS_XVPICKVE2GR_W,
	LoongArch_INS_XVPICKVE2GR_WU,
	LoongArch_INS_XVPICKVE_D,
	LoongArch_INS_XVPICKVE_W,
	LoongArch_INS_XVREPL128VEI_B,
	LoongArch_INS_XVREPL128VEI_D,
	LoongArch_INS_XVREPL128VEI_H,
	LoongArch_INS_XVREPL128VEI_W,
	LoongArch_INS_XVREPLGR2VR_B,
	LoongArch_INS_XVREPLGR2VR_D,
	LoongArch_INS_XVREPLGR2VR_H,
	LoongArch_INS_XVREPLGR2VR_W,
	LoongArch_INS_XVREPLVE0_B,
	LoongArch_INS_XVREPLVE0_D,
	LoongArch_INS_XVREPLVE0_H,
	LoongArch_INS_XVREPLVE0_Q,
	LoongArch_INS_XVREPLVE0_W,
	LoongArch_INS_XVREPLVE_B,
	LoongArch_INS_XVREPLVE_D,
	LoongArch_INS_XVREPLVE_H,
	LoongArch_INS_XVREPLVE_W,
	LoongArch_INS_XVROTRI_B,
	LoongArch_INS_XVROTRI_D,
	LoongArch_INS_XVROTRI_H,
	LoongArch_INS_XVROTRI_W,
	LoongArch_INS_XVROTR_B,
	LoongArch_INS_XVROTR_D,
	LoongArch_INS_XVROTR_H,
	LoongArch_INS_XVROTR_W,
	LoongArch_INS_XVSADD_B,
	LoongArch_INS_XVSADD_BU,
	LoongArch_INS_XVSADD_D,
	LoongArch_INS_XVSADD_DU,
	LoongArch_INS_XVSADD_H,
	LoongArch_INS_XVSADD_HU,
	LoongArch_INS_XVSADD_W,
	LoongArch_INS_XVSADD_WU,
	LoongArch_INS_XVSAT_B,
	LoongArch_INS_XVSAT_BU,
	LoongArch_INS_XVSAT_D,
	LoongArch_INS_XVSAT_DU,
	LoongArch_INS_XVSAT_H,
	LoongArch_INS_XVSAT_HU,
	LoongArch_INS_XVSAT_W,
	LoongArch_INS_XVSAT_WU,
	LoongArch_INS_XVSEQI_B,
	LoongArch_INS_XVSEQI_D,
	LoongArch_INS_XVSEQI_H,
	LoongArch_INS_XVSEQI_W,
	LoongArch_INS_XVSEQ_B,
	LoongArch_INS_XVSEQ_D,
	LoongArch_INS_XVSEQ_H,
	LoongArch_INS_XVSEQ_W,
	LoongArch_INS_XVSETALLNEZ_B,
	LoongArch_INS_XVSETALLNEZ_D,
	LoongArch_INS_XVSETALLNEZ_H,
	LoongArch_INS_XVSETALLNEZ_W,
	LoongArch_INS_XVSETANYEQZ_B,
	LoongArch_INS_XVSETANYEQZ_D,
	LoongArch_INS_XVSETANYEQZ_H,
	LoongArch_INS_XVSETANYEQZ_W,
	LoongArch_INS_XVSETEQZ_V,
	LoongArch_INS_XVSETNEZ_V,
	LoongArch_INS_XVSHUF4I_B,
	LoongArch_INS_XVSHUF4I_D,
	LoongArch_INS_XVSHUF4I_H,
	LoongArch_INS_XVSHUF4I_W,
	LoongArch_INS_XVSHUF_B,
	LoongArch_INS_XVSHUF_D,
	LoongArch_INS_XVSHUF_H,
	LoongArch_INS_XVSHUF_W,
	LoongArch_INS_XVSIGNCOV_B,
	LoongArch_INS_XVSIGNCOV_D,
	LoongArch_INS_XVSIGNCOV_H,
	LoongArch_INS_XVSIGNCOV_W,
	LoongArch_INS_XVSLEI_B,
	LoongArch_INS_XVSLEI_BU,
	LoongArch_INS_XVSLEI_D,
	LoongArch_INS_XVSLEI_DU,
	LoongArch_INS_XVSLEI_H,
	LoongArch_INS_XVSLEI_HU,
	LoongArch_INS_XVSLEI_W,
	LoongArch_INS_XVSLEI_WU,
	LoongArch_INS_XVSLE_B,
	LoongArch_INS_XVSLE_BU,
	LoongArch_INS_XVSLE_D,
	LoongArch_INS_XVSLE_DU,
	LoongArch_INS_XVSLE_H,
	LoongArch_INS_XVSLE_HU,
	LoongArch_INS_XVSLE_W,
	LoongArch_INS_XVSLE_WU,
	LoongArch_INS_XVSLLI_B,
	LoongArch_INS_XVSLLI_D,
	LoongArch_INS_XVSLLI_H,
	LoongArch_INS_XVSLLI_W,
	LoongArch_INS_XVSLLWIL_DU_WU,
	LoongArch_INS_XVSLLWIL_D_W,
	LoongArch_INS_XVSLLWIL_HU_BU,
	LoongArch_INS_XVSLLWIL_H_B,
	LoongArch_INS_XVSLLWIL_WU_HU,
	LoongArch_INS_XVSLLWIL_W_H,
	LoongArch_INS_XVSLL_B,
	LoongArch_INS_XVSLL_D,
	LoongArch_INS_XVSLL_H,
	LoongArch_INS_XVSLL_W,
	LoongArch_INS_XVSLTI_B,
	LoongArch_INS_XVSLTI_BU,
	LoongArch_INS_XVSLTI_D,
	LoongArch_INS_XVSLTI_DU,
	LoongArch_INS_XVSLTI_H,
	LoongArch_INS_XVSLTI_HU,
	LoongArch_INS_XVSLTI_W,
	LoongArch_INS_XVSLTI_WU,
	LoongArch_INS_XVSLT_B,
	LoongArch_INS_XVSLT_BU,
	LoongArch_INS_XVSLT_D,
	LoongArch_INS_XVSLT_DU,
	LoongArch_INS_XVSLT_H,
	LoongArch_INS_XVSLT_HU,
	LoongArch_INS_XVSLT_W,
	LoongArch_INS_XVSLT_WU,
	LoongArch_INS_XVSRAI_B,
	LoongArch_INS_XVSRAI_D,
	LoongArch_INS_XVSRAI_H,
	LoongArch_INS_XVSRAI_W,
	LoongArch_INS_XVSRANI_B_H,
	LoongArch_INS_XVSRANI_D_Q,
	LoongArch_INS_XVSRANI_H_W,
	LoongArch_INS_XVSRANI_W_D,
	LoongArch_INS_XVSRAN_B_H,
	LoongArch_INS_XVSRAN_H_W,
	LoongArch_INS_XVSRAN_W_D,
	LoongArch_INS_XVSRARI_B,
	LoongArch_INS_XVSRARI_D,
	LoongArch_INS_XVSRARI_H,
	LoongArch_INS_XVSRARI_W,
	LoongArch_INS_XVSRARNI_B_H,
	LoongArch_INS_XVSRARNI_D_Q,
	LoongArch_INS_XVSRARNI_H_W,
	LoongArch_INS_XVSRARNI_W_D,
	LoongArch_INS_XVSRARN_B_H,
	LoongArch_INS_XVSRARN_H_W,
	LoongArch_INS_XVSRARN_W_D,
	LoongArch_INS_XVSRAR_B,
	LoongArch_INS_XVSRAR_D,
	LoongArch_INS_XVSRAR_H,
	LoongArch_INS_XVSRAR_W,
	LoongArch_INS_XVSRA_B,
	LoongArch_INS_XVSRA_D,
	LoongArch_INS_XVSRA_H,
	LoongArch_INS_XVSRA_W,
	LoongArch_INS_XVSRLI_B,
	LoongArch_INS_XVSRLI_D,
	LoongArch_INS_XVSRLI_H,
	LoongArch_INS_XVSRLI_W,
	LoongArch_INS_XVSRLNI_B_H,
	LoongArch_INS_XVSRLNI_D_Q,
	LoongArch_INS_XVSRLNI_H_W,
	LoongArch_INS_XVSRLNI_W_D,
	LoongArch_INS_XVSRLN_B_H,
	LoongArch_INS_XVSRLN_H_W,
	LoongArch_INS_XVSRLN_W_D,
	LoongArch_INS_XVSRLRI_B,
	LoongArch_INS_XVSRLRI_D,
	LoongArch_INS_XVSRLRI_H,
	LoongArch_INS_XVSRLRI_W,
	LoongArch_INS_XVSRLRNI_B_H,
	LoongArch_INS_XVSRLRNI_D_Q,
	LoongArch_INS_XVSRLRNI_H_W,
	LoongArch_INS_XVSRLRNI_W_D,
	LoongArch_INS_XVSRLRN_B_H,
	LoongArch_INS_XVSRLRN_H_W,
	LoongArch_INS_XVSRLRN_W_D,
	LoongArch_INS_XVSRLR_B,
	LoongArch_INS_XVSRLR_D,
	LoongArch_INS_XVSRLR_H,
	LoongArch_INS_XVSRLR_W,
	LoongArch_INS_XVSRL_B,
	LoongArch_INS_XVSRL_D,
	LoongArch_INS_XVSRL_H,
	LoongArch_INS_XVSRL_W,
	LoongArch_INS_XVSSRANI_BU_H,
	LoongArch_INS_XVSSRANI_B_H,
	LoongArch_INS_XVSSRANI_DU_Q,
	LoongArch_INS_XVSSRANI_D_Q,
	LoongArch_INS_XVSSRANI_HU_W,
	LoongArch_INS_XVSSRANI_H_W,
	LoongArch_INS_XVSSRANI_WU_D,
	LoongArch_INS_XVSSRANI_W_D,
	LoongArch_INS_XVSSRAN_BU_H,
	LoongArch_INS_XVSSRAN_B_H,
	LoongArch_INS_XVSSRAN_HU_W,
	LoongArch_INS_XVSSRAN_H_W,
	LoongArch_INS_XVSSRAN_WU_D,
	LoongArch_INS_XVSSRAN_W_D,
	LoongArch_INS_XVSSRARNI_BU_H,
	LoongArch_INS_XVSSRARNI_B_H,
	LoongArch_INS_XVSSRARNI_DU_Q,
	LoongArch_INS_XVSSRARNI_D_Q,
	LoongArch_INS_XVSSRARNI_HU_W,
	LoongArch_INS_XVSSRARNI_H_W,
	LoongArch_INS_XVSSRARNI_WU_D,
	LoongArch_INS_XVSSRARNI_W_D,
	LoongArch_INS_XVSSRARN_BU_H,
	LoongArch_INS_XVSSRARN_B_H,
	LoongArch_INS_XVSSRARN_HU_W,
	LoongArch_INS_XVSSRARN_H_W,
	LoongArch_INS_XVSSRARN_WU_D,
	LoongArch_INS_XVSSRARN_W_D,
	LoongArch_INS_XVSSRLNI_BU_H,
	LoongArch_INS_XVSSRLNI_B_H,
	LoongArch_INS_XVSSRLNI_DU_Q,
	LoongArch_INS_XVSSRLNI_D_Q,
	LoongArch_INS_XVSSRLNI_HU_W,
	LoongArch_INS_XVSSRLNI_H_W,
	LoongArch_INS_XVSSRLNI_WU_D,
	LoongArch_INS_XVSSRLNI_W_D,
	LoongArch_INS_XVSSRLN_BU_H,
	LoongArch_INS_XVSSRLN_B_H,
	LoongArch_INS_XVSSRLN_HU_W,
	LoongArch_INS_XVSSRLN_H_W,
	LoongArch_INS_XVSSRLN_WU_D,
	LoongArch_INS_XVSSRLN_W_D,
	LoongArch_INS_XVSSRLRNI_BU_H,
	LoongArch_INS_XVSSRLRNI_B_H,
	LoongArch_INS_XVSSRLRNI_DU_Q,
	LoongArch_INS_XVSSRLRNI_D_Q,
	LoongArch_INS_XVSSRLRNI_HU_W,
	LoongArch_INS_XVSSRLRNI_H_W,
	LoongArch_INS_XVSSRLRNI_WU_D,
	LoongArch_INS_XVSSRLRNI_W_D,
	LoongArch_INS_XVSSRLRN_BU_H,
	LoongArch_INS_XVSSRLRN_B_H,
	LoongArch_INS_XVSSRLRN_HU_W,
	LoongArch_INS_XVSSRLRN_H_W,
	LoongArch_INS_XVSSRLRN_WU_D,
	LoongArch_INS_XVSSRLRN_W_D,
	LoongArch_INS_XVSSUB_B,
	LoongArch_INS_XVSSUB_BU,
	LoongArch_INS_XVSSUB_D,
	LoongArch_INS_XVSSUB_DU,
	LoongArch_INS_XVSSUB_H,
	LoongArch_INS_XVSSUB_HU,
	LoongArch_INS_XVSSUB_W,
	LoongArch_INS_XVSSUB_WU,
	LoongArch_INS_XVST,
	LoongArch_INS_XVSTELM_B,
	LoongArch_INS_XVSTELM_D,
	LoongArch_INS_XVSTELM_H,
	LoongArch_INS_XVSTELM_W,
	LoongArch_INS_XVSTX,
	LoongArch_INS_XVSUBI_BU,
	LoongArch_INS_XVSUBI_DU,
	LoongArch_INS_XVSUBI_HU,
	LoongArch_INS_XVSUBI_WU,
	LoongArch_INS_XVSUBWEV_D_W,
	LoongArch_INS_XVSUBWEV_D_WU,
	LoongArch_INS_XVSUBWEV_H_B,
	LoongArch_INS_XVSUBWEV_H_BU,
	LoongArch_INS_XVSUBWEV_Q_D,
	LoongArch_INS_XVSUBWEV_Q_DU,
	LoongArch_INS_XVSUBWEV_W_H,
	LoongArch_INS_XVSUBWEV_W_HU,
	LoongArch_INS_XVSUBWOD_D_W,
	LoongArch_INS_XVSUBWOD_D_WU,
	LoongArch_INS_XVSUBWOD_H_B,
	LoongArch_INS_XVSUBWOD_H_BU,
	LoongArch_INS_XVSUBWOD_Q_D,
	LoongArch_INS_XVSUBWOD_Q_DU,
	LoongArch_INS_XVSUBWOD_W_H,
	LoongArch_INS_XVSUBWOD_W_HU,
	LoongArch_INS_XVSUB_B,
	LoongArch_INS_XVSUB_D,
	LoongArch_INS_XVSUB_H,
	LoongArch_INS_XVSUB_Q,
	LoongArch_INS_XVSUB_W,
	LoongArch_INS_XVXORI_B,
	LoongArch_INS_XVXOR_V,

	// clang-format on
	// generated content <LoongArchGenCSInsnEnum.inc> end

	LOONGARCH_INS_ENDING,
} loongarch_insn;

//> Group of LOONGARCH instructions
typedef enum loongarch_insn_group {
	LoongArch_GRP_INVALID = 0, ///< = CS_GRP_INVALID

	/// Generic groups
	/// all jump instructions (conditional+direct+indirect jumps)
	LoongArch_GRP_JUMP, ///< = CS_GRP_JUMP
	/// all call instructions
	LoongArch_GRP_CALL, ///< = CS_GRP_CALL
	/// all return instructions
	LoongArch_GRP_RET, ///< = CS_GRP_RET
	/// all interrupt instructions (int+syscall)
	LoongArch_GRP_INT, ///< = CS_GRP_INT
	/// all interrupt return instructions
	LoongArch_GRP_IRET, ///< = CS_GRP_IRET
	/// all privileged instructions
	LoongArch_GRP_PRIVILEGE, ///< = CS_GRP_PRIVILEGE
	/// all relative branching instructions
	LoongArch_GRP_BRANCH_RELATIVE, ///< = CS_GRP_BRANCH_RELATIVE

	// Architecture-specific groups
	// generated content <LoongArchGenCSFeatureEnum.inc> begin
	// clang-format off

LoongArch_FEATURE_IsLA64 = 128,
	LoongArch_FEATURE_IsLA32,
	LoongArch_FEATURE_HasLaGlobalWithPcrel,
	LoongArch_FEATURE_HasLaGlobalWithAbs,
	LoongArch_FEATURE_HasLaLocalWithAbs,

	// clang-format on
	// generated content <LoongArchGenCSFeatureEnum.inc> end

	LOONGARCH_GRP_ENDING,
} loongarch_insn_group;

#ifdef __cplusplus
}
#endif

#endif
