name: CMake

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-20.04
          - windows-2022
        include:
          - os: windows-2022
            platform: windows
          - os: ubuntu-20.04
            platform: linux
          - os: macOS-latest
            platform: macos

    steps:

    - uses: actions/checkout@v3

    - uses: lukka/get-cmake@latest
      name: Get CMake

    - uses: ilammy/msvc-dev-cmd@v1  
      name: Setup Windows dev environment
      with:
        arch: 'x64'
      if: ${{ matrix.platform == 'windows' }}

    - name: 'Configure, Build and Install'
      run: |
        cmake --preset=${{ matrix.platform }}-x64
        cmake --build --preset build-${{ matrix.platform }}
        cmake --build --preset install-${{ matrix.platform }}
